USE space_exploration_db;

START TRANSACTION;

-- =========================================================================
-- 1. Master Data: Agencies (Space Agencies / Operators)
-- =========================================================================
INSERT INTO agencies (agency_id, source_provider, source_id, name, abbrev, country_code, image_url) VALUES
(1, 'll2', 'ag-101', 'National Aeronautics and Space Administration', 'NASA', 'USA', 'https://images.example.com/agencies/nasa.png'),
(2, 'll2', 'ag-102', 'European Space Agency', 'ESA', 'EUR', 'https://images.example.com/agencies/esa.png'),
(3, 'll2', 'ag-103', 'Japan Aerospace Exploration Agency', 'JAXA', 'JPN', 'https://images.example.com/agencies/jaxa.png'),
(4, 'll2', 'ag-104', 'Space Exploration Technologies Corp.', 'SpaceX', 'USA', 'https://images.example.com/agencies/spacex.png'),
(5, 'll2', 'ag-105', 'Indian Space Research Organisation', 'ISRO', 'IND', 'https://images.example.com/agencies/isro.png');

-- =========================================================================
-- 2. Master Data: Launches (~20 Launch Events)
-- =========================================================================
INSERT INTO launches (launch_id, source_provider, source_id, name, net, status, image_url, window_start, window_end) VALUES
(1, 'll2', 'a1b2c3d4-e5f6-7a8b-9c0d-1e2f3a4b5c6d', 'Artemis IV SLS Flight', '2028-09-12 04:30:00', 'Scheduled', 'https://images.example.com/launches/sls.jpg', '2028-09-12 04:00:00', '2028-09-12 06:00:00'),
(2, 'll2', 'b2c3d4e5-f6a7-8b9c-0d1e-2f3a4b5c6d7e', 'Ariane 6 Heavy Maiden', '2027-05-20 18:15:00', 'Success', 'https://images.example.com/launches/ariane6.jpg', '2027-05-20 18:00:00', '2027-05-20 20:00:00'),
(3, 'll2', 'c3d4e5f6-a7b8-9c0d-1e2f-3a4b5c6d7e8f', 'H3-24W Lunar Dispatch', '2027-11-05 22:00:00', 'Scheduled', 'https://images.example.com/launches/h3.jpg', '2027-11-05 21:30:00', '2027-11-05 22:30:00'),
(4, 'll2', 'd4e5f6a7-b8c9-0d1e-2f3a-4b5c6d7e8f9a', 'Falcon Heavy Interplanetary', '2026-10-15 14:00:00', 'Success', 'https://images.example.com/launches/fh.jpg', '2026-10-15 13:45:00', '2026-10-15 15:30:00'),
(5, 'll2', 'e5f6a7b8-c9d0-1e2f-3a4b-5c6d7e8f9a0b', 'PSLV-C61 Dedicated Payload', '2026-08-30 06:20:00', 'Success', 'https://images.example.com/launches/pslv.jpg', '2026-08-30 06:00:00', '2026-08-30 07:00:00'),
(6, 'll2', 'f6a7b8c9-d0e1-2f3a-4b5c-6d7e8f9a0b1c', 'Starship Integrated Flight Test 8', '2026-12-10 13:00:00', 'Scheduled', 'https://images.example.com/launches/starship.jpg', '2026-12-10 12:30:00', '2026-12-10 15:00:00'),
(7, 'll2', 'a7b8c9d0-e1f2-3a4b-5c6d-7e8f9a0b1c2d', 'Atlas V 551 National Security', '2027-01-18 09:10:00', 'Scheduled', 'https://images.example.com/launches/atlasv.jpg', '2027-01-18 09:00:00', '2027-01-18 11:00:00'),
(8, 'll2', 'b8c9d0e1-f2a3-4b5c-6d7e-8f9a0b1c2d3e', 'Vulcan Centaur Certification-3', '2027-03-25 11:45:00', 'Scheduled', 'https://images.example.com/launches/vulcan.jpg', '2027-03-25 11:30:00', '2027-03-25 13:30:00'),
(9, 'll2', 'c9d0e1f2-a3b4-5c6d-7e8f-9a0b1c2d3e4f', 'Falcon 9 Starlink Group 12-4', '2026-10-02 02:15:00', 'Success', 'https://images.example.com/launches/f9.jpg', '2026-10-02 02:00:00', '2026-10-02 04:00:00'),
(10, 'll2', 'd0e1f2a3-b4c5-6d7e-8f9a-0b1c2d3e4f5a', 'Soyuz-2.1b Glonass Meridian', '2026-11-14 06:50:00', 'Scheduled', 'https://images.example.com/launches/soyuz.jpg', '2026-11-14 06:30:00', '2026-11-14 08:00:00'),
(11, 'll2', 'e1f2a3b4-c5d6-7e8f-9a0b-1c2d3e4f5a6b', 'Long March 5B Core Module', '2027-06-01 15:00:00', 'Scheduled', 'https://images.example.com/launches/cz5.jpg', '2027-06-01 14:30:00', '2027-06-01 16:30:00'),
(12, 'll2', 'f2a3b4c5-d6e7-8f9a-0b1c-2d3e4f5a6b7c', 'Electron Deep Space Return', '2027-04-12 21:00:00', 'Scheduled', 'https://images.example.com/launches/electron.jpg', '2027-04-12 20:30:00', '2027-04-12 22:30:00'),
(13, 'll2', 'a3b4c5d6-e7f8-9a0b-1c2d-3e4f5a6b7c8d', 'GSLV Mk II NavIC Navigation Payload', '2026-11-28 08:00:00', 'Scheduled', 'https://images.example.com/launches/gslv.jpg', '2026-11-28 07:30:00', '2026-11-28 09:30:00'),
(14, 'll2', 'b4c5d6e7-f8a9-0b1c-2d3e-4f5a6b7c8d9e', 'Delta IV Heavy Final Legacy Flight', '2025-04-09 16:53:00', 'Success', 'https://images.example.com/launches/deltaiv.jpg', '2025-04-09 16:00:00', '2025-04-09 19:00:00'),
(15, 'll2', 'c5d6e7f8-a9b0-1c2d-3e4f-5a6b7c8d9e0f', 'H3 Flight No. 5 Earth Observation', '2027-02-15 01:30:00', 'Scheduled', 'https://images.example.com/launches/h3_5.jpg', '2027-02-15 01:00:00', '2027-02-15 03:00:00'),
(16, 'll2', 'd6e7f8a9-b0c1-2d3e-4f5a-6b7c8d9e0f1a', 'Vega-C Resumption Mission', '2026-12-20 22:40:00', 'Scheduled', 'https://images.example.com/launches/vegac.jpg', '2026-12-20 22:00:00', '2027-12-21 00:00:00'),
(17, 'll2', 'e7f8a9b0-c1d2-3e4f-5a6b-7c8d9e0f1a2b', 'New Glenn Maiden Flight', '2026-11-01 14:00:00', 'Scheduled', 'https://images.example.com/launches/newglenn.jpg', '2026-11-01 13:00:00', '2026-11-01 17:00:00'),
(18, 'll2', 'f8a9b0c1-d2e3-4f5a-6b7c-8d9e0f1a2b3c', 'Firefly Alpha Commercial Sortie', '2027-01-10 03:20:00', 'Scheduled', 'https://images.example.com/launches/alpha.jpg', '2027-01-10 03:00:00', '2027-01-10 05:00:00'),
(19, 'll2', 'a9b0c1d2-e3f4-5a6b-7c8d-9e0f1a2b3c4d', 'LVM3 Commercial Multi-Satellite', '2027-07-15 10:00:00', 'Scheduled', 'https://images.example.com/launches/lvm3.jpg', '2027-07-15 09:30:00', '2027-07-15 11:30:00'),
(20, 'll2', 'b0c1d2e3-f4a5-6b7c-8d9e-0f1a2b3c4d5e', 'SLS Block 1B Lunar Crew Launch', '2029-05-10 02:00:00', 'Scheduled', 'https://images.example.com/launches/slsb1b.jpg', '2029-05-10 01:30:00', '2029-05-10 04:00:00');

-- =========================================================================
-- 3. Master Data: Spacecraft (~150 Variations)
-- =========================================================================
INSERT INTO spacecraft (spacecraft_id, source_provider, source_id, name, spacecraft_type, image_url) VALUES
(101, 'll2', 'sc-301', 'Orion Deep Space Variant', 'Crew Capsule', 'https://images.example.com/sc/orion.jpg'),
(102, 'll2', 'sc-302', 'BepiColombo MTM', 'Ion Propulsion Module', 'https://images.example.com/sc/bepi.jpg'),
(103, 'll2', 'sc-303', 'LUPEX Rover Prototype', 'Surface Rover', 'https://images.example.com/sc/lupex.jpg'),
(104, 'll2', 'sc-304', 'Dragon XL Cargo', 'Logistics Resupply', 'https://images.example.com/sc/dragonxl.jpg'),
(105, 'll2', 'sc-305', 'Aditya-L1 Solar Observatory', 'Scientific Satellite', 'https://images.example.com/sc/aditya.jpg'),
(106, 'll2', 'sc-306', 'ExoMars Trace Orbiter', 'Orbiter', 'https://images.example.com/sc/exomars.jpg'),
(107, 'll2', 'sc-307', 'Huygens Probe Successor', 'Atmospheric Descent Probe', 'https://images.example.com/sc/huygens2.jpg'),
(108, 'll2', 'sc-308', 'Europa Clipper Vault', 'Planetary Orbiter', 'https://images.example.com/sc/clipper.jpg'),
(109, 'll2', 'sc-309', 'Psyche Metal Detector', 'Asteroid Explorer', 'https://images.example.com/sc/psyche.jpg'),
(110, 'll2', 'sc-310', 'Juno-II Radiation Shield', 'Jovian Orbiter', 'https://images.example.com/sc/juno2.jpg'),
(111, 'll2', 'sc-311', 'Viper Lunar Ice Digger', 'Polar Rover', 'https://images.example.com/sc/viper.jpg'),
(112, 'll2', 'sc-312', 'HAKUTO-R M2 Lander', 'Commercial Lander', 'https://images.example.com/sc/hakuto2.jpg'),
(113, 'll2', 'sc-313', 'Blue Ghost Mission 1', 'Lunar Lander', 'https://images.example.com/sc/blueghost.jpg'),
(114, 'll2', 'sc-314', 'IM-2 Nova-C', 'Surface Lander', 'https://images.example.com/sc/novac.jpg'),
(115, 'll2', 'sc-315', 'Mars Sample Return Lander', 'Sample Retrieval Lander', 'https://images.example.com/sc/msrl.jpg'),
(116, 'll2', 'sc-316', 'MRO Successor High-Res', 'Reconnaissance Orbiter', 'https://images.example.com/sc/mro2.jpg'),
(117, 'll2', 'sc-317', 'Phobos Grunt II', 'Sample Return Probe', 'https://images.example.com/sc/phobos2.jpg'),
(118, 'll2', 'sc-318', 'Venus Life Finder', 'Atmospheric Probe', 'https://images.example.com/sc/vlf.jpg'),
(119, 'll2', 'sc-319', 'DAVINCI Descent Sphere', 'Venus Probe', 'https://images.example.com/sc/davinci.jpg'),
(120, 'll2', 'sc-320', 'VERITAS Radar Orbiter', 'Venus Orbiter', 'https://images.example.com/sc/veritas.jpg'),
(121, 'll2', 'sc-321', 'Enclosure Titan Submarine', 'Cryogenic Submersible', 'https://images.example.com/sc/sub.jpg'),
(122, 'll2', 'sc-322', 'Dragonfly Rotorcraft Mk2', 'Nuclear Rotorcraft', 'https://images.example.com/sc/dragonfly2.jpg'),
(123, 'll2', 'sc-323', 'Io Volcanic Observer', 'Jovian Moon Orbiter', 'https://images.example.com/sc/ivo.jpg'),
(124, 'll2', 'sc-324', 'Uranus Orbiter and Probe', 'Ice Giant Flagship', 'https://images.example.com/sc/uranus.jpg'),
(125, 'll2', 'sc-325', 'Neptune Odyssey', 'Flagship Orbiter', 'https://images.example.com/sc/neptune.jpg'),
(126, 'll2', 'sc-326', 'Comet Interceptor Tri-Craft', 'Fast Flyby Array', 'https://images.example.com/sc/cometint.jpg'),
(127, 'll2', 'sc-327', 'DESTINY+ Asteroid Flyby', 'Technology Demonstrator', 'https://images.example.com/sc/destiny.jpg'),
(128, 'll2', 'sc-328', 'MMX Martian Moon Explorer', 'Sample Return Probe', 'https://images.example.com/sc/mmx.jpg'),
(129, 'll2', 'sc-329', 'JUICE Sub-Radar Module', 'Jovian Icy Moons Orbiter', 'https://images.example.com/sc/juice.jpg'),
(130, 'll2', 'sc-330', 'Solar Orbiter Extended', 'Heliophysics Satellite', 'https://images.example.com/sc/solor.jpg'),
(131, 'll2', 'sc-331', 'Parker Solar Probe Plus', 'Solar Probe', 'https://images.example.com/sc/psp.jpg'),
(132, 'll2', 'sc-332', 'STEREO-Next A', 'Solar Terrestrial Observer', 'https://images.example.com/sc/stereoa.jpg'),
(133, 'll2', 'sc-333', 'STEREO-Next B', 'Solar Terrestrial Observer', 'https://images.example.com/sc/stereob.jpg'),
(134, 'll2', 'sc-334', 'IMAP Interstellar Mapper', 'Boundary Explorer', 'https://images.example.com/sc/imap.jpg'),
(135, 'll2', 'sc-335', 'GOLD Ionosphere Watcher', 'Atmospheric Satellite', 'https://images.example.com/sc/gold.jpg'),
(136, 'll2', 'sc-336', 'ICON-2 Aeronomy Sat', 'Ionosphere Explorer', 'https://images.example.com/sc/icon2.jpg'),
(137, 'll2', 'sc-337', 'NISAR Radar Earth Observer', 'SAR Satellite', 'https://images.example.com/sc/nisar.jpg'),
(138, 'll2', 'sc-338', 'SWOT Hydrology Satellite', 'Ocean Altimeter', 'https://images.example.com/sc/swot.jpg'),
(139, 'll2', 'sc-339', 'Sentinel-6 Michael Freilich', 'Oceanography Sat', 'https://images.example.com/sc/sentinel6.jpg'),
(140, 'll2', 'sc-340', 'Landsat 9 Next-Gen', 'Earth Imaging Sat', 'https://images.example.com/sc/landsat9.jpg'),
(141, 'll2', 'sc-341', 'GOES-T Meteorological Sat', 'Weather Satellite', 'https://images.example.com/sc/goest.jpg'),
(142, 'll2', 'sc-342', 'TESS Exoplanet Hunter', 'Space Telescope', 'https://images.example.com/sc/tess.jpg'),
(143, 'll2', 'sc-343', 'James Webb Space Telescope-B', 'Infrared Telescope', 'https://images.example.com/sc/jwst2.jpg'),
(144, 'll2', 'sc-344', 'Nancy Grace Roman Scope', 'Wide-Field Telescope', 'https://images.example.com/sc/roman.jpg'),
(145, 'll2', 'sc-345', 'Chandra X-Ray Successor', 'X-Ray Observatory', 'https://images.example.com/sc/chandra2.jpg'),
(146, 'll2', 'sc-346', 'Compton Gamma Successor', 'Gamma Ray Observatory', 'https://images.example.com/sc/cgro2.jpg'),
(147, 'll2', 'sc-347', 'LISA Gravitational Wave Pathfinder', 'Space Interferometer', 'https://images.example.com/sc/lisa.jpg'),
(148, 'll2', 'sc-348', 'Ariel Exoplanet Characterizer', 'Spectroscopy Sat', 'https://images.example.com/sc/ariel.jpg'),
(149, 'll2', 'sc-349', 'EnviroSat-1', 'Environmental Monitor', 'https://images.example.com/sc/enviro1.jpg'),
(150, 'll2', 'sc-350', 'Astro-H2 Hitomi Replacement', 'X-Ray Astronomy Sat', 'https://images.example.com/sc/astroh2.jpg'),
(151, 'll2', 'sc-351', 'QZS-7 Michibiki Navigation', 'GNSS Satellite', 'https://images.example.com/sc/qzss7.jpg'),
(152, 'll2', 'sc-352', 'IGS-Radar 8', 'Reconnaissance Satellite', 'https://images.example.com/sc/igs8.jpg'),
(153, 'll2', 'sc-353', 'Inmarsat-GX 10', 'Communications Sat', 'https://images.example.com/sc/gx10.jpg'),
(154, 'll2', 'sc-354', 'Oneweb Generation 2', 'Constellation Satellite', 'https://images.example.com/sc/ow2.jpg'),
(155, 'll2', 'sc-355', 'Starlink V2 Mini Pro', 'Broadband Satellite', 'https://images.example.com/sc/slv2.jpg'),
(156, 'll2', 'sc-356', 'Kuiper Prototype Sat 1', 'Internet Satellite', 'https://images.example.com/sc/kuiper1.jpg'),
(157, 'll2', 'sc-357', 'Iridium NEXT-2', 'Mobile Comms Sat', 'https://images.example.com/sc/iridium2.jpg'),
(158, 'll2', 'sc-358', 'WorldView Legion 3', 'High-Res Earth Imaging', 'https://images.example.com/sc/wvlegion3.jpg'),
(159, 'll2', 'sc-359', 'SkySat-C Successor', 'Commercial Optical Sat', 'https://images.example.com/sc/skysat.jpg'),
(160, 'll2', 'sc-360', 'PlanetScope Dove-X', 'Nanosatellite', 'https://images.example.com/sc/dovex.jpg'),
(161, 'll2', 'sc-361', 'Spire Global Lemur-3', 'Weather Radio Occultation', 'https://images.example.com/sc/lemur3.jpg'),
(162, 'll2', 'sc-362', 'Capella SAR Block 3', 'Radar Imaging Sat', 'https://images.example.com/sc/capella3.jpg'),
(163, 'll2', 'sc-363', 'ICEYE X-Band SAR 12', 'Micro-SAR Satellite', 'https://images.example.com/sc/iceye12.jpg'),
(164, 'll2', 'sc-364', 'GHGSat-C Elite', 'Emissions Monitor', 'https://images.example.com/sc/ghgsat.jpg'),
(165, 'll2', 'sc-365', 'BlackSky Global 10', 'Optical Recon Sat', 'https://images.example.com/sc/blacksky10.jpg'),
(166, 'll2', 'sc-366', 'Umbra SAR Advanced', 'Synthetic Aperture Radar', 'https://images.example.com/sc/umbra.jpg'),
(167, 'll2', 'sc-367', 'Varda W-Series Capsule', 'In-Space Manufacturing', 'https://images.example.com/sc/varda.jpg'),
(168, 'll2', 'sc-368', 'Sierra Space Dream Chaser Cargo', 'Spaceplane', 'https://images.example.com/sc/dreamchaser.jpg'),
(169, 'll2', 'sc-369', 'CST-100 Starliner Block 2', 'Crew Capsule', 'https://images.example.com/sc/starliner2.jpg'),
(170, 'll2', 'sc-370', 'Federation Crew Ship', 'Next-Gen Crew Capsule', 'https://images.example.com/sc/federation.jpg'),
(171, 'll2', 'sc-371', 'Gaganyaan Uncrewed Test 3', 'Human Spaceflight Capsule', 'https://images.example.com/sc/gaganyan3.jpg'),
(172, 'll2', 'sc-372', 'Shenzhou 20 Orbital Module', 'Crew Module', 'https://images.example.com/sc/shenzhou20.jpg'),
(173, 'll2', 'sc-373', 'Tianzhou 9 Cargo Craft', 'Resupply Spacecraft', 'https://images.example.com/sc/tianzhou9.jpg'),
(174, 'll2', 'sc-374', 'Progress MS-32', 'Automatic Resupply Ship', 'https://images.example.com/sc/progress32.jpg'),
(175, 'll2', 'sc-375', 'Cygnus NG-23', 'Cargo Resupply Vehicle', 'https://images.example.com/sc/cygnus23.jpg'),
(176, 'll2', 'sc-376', 'HTV-X Spacecraft 3', 'Uncrewed Cargo Carrier', 'https://images.example.com/sc/htvx3.jpg'),
(177, 'll2', 'sc-377', 'ATV Successor Tug', 'Orbital Transfer Vehicle', 'https://images.example.com/sc/atv2.jpg'),
(178, 'll2', 'sc-378', 'MEV-3 Life Extension Vehicle', 'Satellite Servicer', 'https://images.example.com/sc/mev3.jpg'),
(179, 'll2', 'sc-379', 'RSV-1 Active Debris Remover', 'Active Debris Removal', 'https://images.example.com/sc/rsv1.jpg'),
(180, 'll2', 'sc-380', 'ClearSpace-1 Harpoon Sat', 'Debris Capture Craft', 'https://images.example.com/sc/clearspace1.jpg'),
(181, 'll2', 'sc-381', 'Astroscale ELSA-M Servicer', 'Docking Demonstrator', 'https://images.example.com/sc/elsam.jpg'),
(182, 'll2', 'sc-382', 'Orbit Fab Gas Station 2', 'Fuel Depot Spacecraft', 'https://images.example.com/sc/orbitfab2.jpg'),
(183, 'll2', 'sc-383', 'Transporter Orbital Tug', 'Rideshare Dispenser', 'https://images.example.com/sc/tug.jpg'),
(184, 'll2', 'sc-384', 'Vigoride Extended', 'Space Tug', 'https://images.example.com/sc/vigoride.jpg'),
(185, 'll2', 'sc-385', 'ION Satellite Carrier SC-V', 'Deployment Platform', 'https://images.example.com/sc/ion.jpg'),
(186, 'll2', 'sc-386', 'Sherpa-LTC Space Vehicle', 'Transfer Vehicle', 'https://images.example.com/sc/sherpalts.jpg'),
(187, 'll2', 'sc-387', 'Curiosity Rover Active Unit', 'Mars Rover', 'https://images.example.com/sc/curiosity.jpg'),
(188, 'll2', 'sc-388', 'Perseverance Backup Unit', 'Mars Astrobiology Rover', 'https://images.example.com/sc/perseverance.jpg'),
(189, 'll2', 'sc-389', 'Zhurong Successor Rover', 'Martian Rover', 'https://images.example.com/sc/zhurong2.jpg'),
(190, 'll2', 'sc-390', 'Rosalind Franklin Rover', 'ExoMars Surface Asset', 'https://images.example.com/sc/rosalind.jpg'),
(191, 'll2', 'sc-391', 'Chandrayaan-4 Ascent Module', 'Lunar Ascent Stage', 'https://images.example.com/sc/ch4ascent.jpg'),
(192, 'll2', 'sc-392', 'Chang''e 7 Hopper Probe', 'Lunar Ice Prospector', 'https://images.example.com/sc/ce7hopper.jpg'),
(193, 'll2', 'sc-393', 'Chang''e 8 Base Constructor', '3D Printing Test Unit', 'https://images.example.com/sc/ce8base.jpg'),
(194, 'll2', 'sc-394', 'Luna-27 Landing Platform', 'Lunar Science Lander', 'https://images.example.com/sc/luna27.jpg'),
(195, 'll2', 'sc-395', 'Mars Ice Mapper Orbiter', 'Subsurface Water Finder', 'https://images.example.com/sc/mim.jpg'),
(196, 'll2', 'sc-396', 'MMX Rover Unit', 'Phobos Surface Rover', 'https://images.example.com/sc/mmxrover.jpg'),
(197, 'll2', 'sc-397', 'JUICE Sub-Surface Radar', 'Ice Penetrator', 'https://images.example.com/sc/juiceradar.jpg'),
(198, 'll2', 'sc-398', 'Titanium Aeroshell Testbed', 'Atmospheric Entry Shield', 'https://images.example.com/sc/aeroshell.jpg'),
(199, 'll2', 'sc-399', 'Solar Sail NanoSat 3', 'Photon Propulsion Demo', 'https://images.example.com/sc/sail3.jpg'),
(200, 'll2', 'sc-400', 'CubeSat Deep Space 2', 'Interplanetary Nanosat', 'https://images.example.com/sc/ds2.jpg'),
(201, 'll2', 'sc-401', 'Artemis Lunar Gateway Habitation Module', 'Space Station Component', 'https://images.example.com/sc/gateway_hab.jpg'),
(202, 'll2', 'sc-402', 'Artemis Lunar Gateway Power and Propulsion', 'Space Station Component', 'https://images.example.com/sc/gateway_ppe.jpg'),
(203, 'll2', 'sc-403', 'Axiom Station Segment AX-1', 'Commercial Space Station', 'https://images.example.com/sc/ax1.jpg'),
(204, 'll2', 'sc-404', 'Orbital Reef Core Module', 'Commercial Outpost', 'https://images.example.com/sc/reef.jpg'),
(205, 'll2', 'sc-405', 'Starlab Commercial Habitat', 'Inflatable Station Module', 'https://images.example.com/sc/starlab.jpg'),
(206, 'll2', 'sc-406', 'Tiangong Expansion Module', 'Space Station Node', 'https://images.example.com/sc/tgg_node.jpg'),
(207, 'll2', 'sc-407', 'MIR-2 Successor Core', 'Modular Space Station', 'https://images.example.com/sc/mir2.jpg'),
(208, 'll2', 'sc-408', 'Inflatable Lunar Habitat Demo', 'Surface Shelter', 'https://images.example.com/sc/inhabit.jpg'),
(209, 'll2', 'sc-409', 'Solar Power Satellite Demo', 'Space-Based Solar Power', 'https://images.example.com/sc/sps.jpg'),
(210, 'll2', 'sc-410', 'Asteroid Mining Prospector Alpha', 'Resource Extraction Scout', 'https://images.example.com/sc/minialpha.jpg'),
(211, 'll2', 'sc-411', 'Lunar Oxygen Extraction Plant', 'In-Situ Resource Unit', 'https://images.example.com/sc/isru_ox.jpg'),
(212, 'll2', 'sc-412', 'Water Electrolysis Power Unit', 'Propellant Production Unit', 'https://images.example.com/sc/electrolysis.jpg'),
(213, 'll2', 'sc-413', 'Nuclear Thermal Propulsion Stage', 'Interplanetary Engine', 'https://images.example.com/sc/ntp.jpg'),
(214, 'll2', 'sc-414', 'Nuclear Electric Propulsion Tug', 'Deep Space Tug', 'https://images.example.com/sc/nep.jpg'),
(215, 'll2', 'sc-415', 'Laser Thermal Propulsion Demo', 'Beamed Energy Propulsion', 'https://images.example.com/sc/ltp.jpg'),
(216, 'll2', 'sc-416', 'Quantum Key Distribution Sat QEYSSAT', 'Security Satellite', 'https://images.example.com/sc/qeyssat.jpg'),
(217, 'll2', 'sc-417', 'Optical Ground Station Link Sat', 'Laser Comms Relay', 'https://images.example.com/sc/ogsl.jpg'),
(218, 'll2', 'sc-418', 'Deep Space Atomic Clock 2', 'Navigation Satellite', 'https://images.example.com/sc/dsac2.jpg'),
(219, 'll2', 'sc-419', 'Pulsar Navigation Testbed', 'X-Ray Nav Sat', 'https://images.example.com/sc/xnav.jpg'),
(220, 'll2', 'sc-420', 'Autonomous Rendezvous NanoSat', 'Docking Test Unit', 'https://images.example.com/sc/arn.jpg'),
(221, 'll2', 'sc-421', 'Suborbital Reusable Launcher Stage', 'Experimental Spaceplane', 'https://images.example.com/sc/suborbital.jpg'),
(222, 'll2', 'sc-422', 'Hypersonic Scramjet Flight Testbed', 'Atmospheric Vehicle', 'https://images.example.com/sc/scramjet.jpg'),
(223, 'll2', 'sc-423', 'Stratospheric Balloon Platform', 'Near-Space Platform', 'https://images.example.com/sc/balloon.jpg'),
(224, 'll2', 'sc-424', 'Mars Helicopter Ingenuity Successor', 'Aero Drone', 'https://images.example.com/sc/helo2.jpg'),
(225, 'll2', 'sc-425', 'Venus Wind Hopper', 'Atmospheric Hopper', 'https://images.example.com/sc/hopper.jpg'),
(226, 'll2', 'sc-426', 'Titan Sailboat Prototype', 'Surface Explorer', 'https://images.example.com/sc/sail.jpg'),
(227, 'll2', 'sc-427', 'Europa Sub-Ice Melt Probe', 'Cryobot', 'https://images.example.com/sc/cryobot.jpg'),
(228, 'll2', 'sc-428', 'Enceladus Vent Harvester', 'Plume Sampler', 'https://images.example.com/sc/harvester.jpg'),
(229, 'll2', 'sc-429', 'Comet Surface Anchoring Harpoon', 'Anchor Mechanism', 'https://images.example.com/sc/harpoon.jpg'),
(230, 'll2', 'sc-430', 'Asteroid Surface Sticky Pad', 'Adhesion Test Unit', 'https://images.example.com/sc/stickypad.jpg'),
(231, 'll2', 'sc-431', 'Lunar Lava Tube Seismic Node 1', 'Seismometer', 'https://images.example.com/sc/seismo1.jpg'),
(232, 'll2', 'sc-432', 'Lunar Lava Tube Seismic Node 2', 'Seismometer', 'https://images.example.com/sc/seismo2.jpg'),
(233, 'll2', 'sc-433', 'Lunar Lava Tube Seismic Node 3', 'Seismometer', 'https://images.example.com/sc/seismo3.jpg'),
(234, 'll2', 'sc-434', 'Mars Dust Storm Monitor A', 'Weather CubeSat', 'https://images.example.com/sc/dust_a.jpg'),
(235, 'll2', 'sc-435', 'Mars Dust Storm Monitor B', 'Weather CubeSat', 'https://images.example.com/sc/dust_b.jpg'),
(236, 'll2', 'sc-436', 'Solar Corona Stereo Probe Alpha', 'Heliophysics Node', 'https://images.example.com/sc/corona_a.jpg'),
(237, 'll2', 'sc-437', 'Solar Corona Stereo Probe Beta', 'Heliophysics Node', 'https://images.example.com/sc/corona_b.jpg'),
(238, 'll2', 'sc-438', 'Jovian Magnetosphere CubeSat 1', 'Magnetometer', 'https://images.example.com/sc/jov_mag1.jpg'),
(239, 'll2', 'sc-439', 'Jovian Magnetosphere CubeSat 2', 'Magnetometer', 'https://images.example.com/sc/jov_mag2.jpg'),
(240, 'll2', 'sc-440', 'Saturn Ring Particle Sampler', 'Ring Density Probe', 'https://images.example.com/sc/ring_samp.jpg'),
(241, 'll2', 'sc-441', 'Kuiper Belt Object Occultation Scout', 'Fast Photometer', 'https://images.example.com/sc/kbo_scout.jpg'),
(242, 'll2', 'sc-442', 'Oort Cloud Trajectory Pathfinder', 'Interstellar Pioneer', 'https://images.example.com/sc/oort.jpg'),
(243, 'll2', 'sc-443', 'Exoplanet Direct Imaging Coronagraph', 'Space Telescope Module', 'https://images.example.com/sc/coronagraph.jpg'),
(244, 'll2', 'sc-444', 'UV Spectroscopic Explorer', 'UV Telescope', 'https://images.example.com/sc/uvspec.jpg'),
(245, 'll2', 'sc-445', 'Far-Side Lunar Radio Telescope', 'Radio Array', 'https://images.example.com/sc/farside_rad.jpg'),
(246, 'll2', 'sc-446', 'Asteroid Defense Kinetic Impactor', 'Deflection Weapon', 'https://images.example.com/sc/impactor.jpg'),
(247, 'll2', 'sc-447', 'Gravity Tractor Tug', 'Gravitational Deflector', 'https://images.example.com/sc/tractor.jpg'),
(248, 'll2', 'sc-448', 'Solar Sail Interplanetary Express', 'Fast Cargo Carrier', 'https://images.example.com/sc/solarsail_exp.jpg'),
(249, 'll2', 'sc-449', 'Laser-Driven LightSail Prototype', 'Relativistic Micro-Probe', 'https://images.example.com/sc/lightsail.jpg'),
(250, 'll2', 'sc-450', 'Deep Space Habitation Centrifuge', 'Artificial Gravity Module', 'https://images.example.com/sc/centrifuge.jpg');

-- =========================================================================
-- 4. Core Missions (100 Unique Records)
-- =========================================================================
INSERT INTO missions (mission_id, source_provider, source_id, name, description, target_body, status, image_url) VALUES
(1, 'll2', 'm-001', 'Lunar South Pole Habitation Scout', 'Deploying advanced seismic sensors and subsurface radar around Shackleton Crater to assess water-ice distribution.', 'Moon', 'planned', 'https://images.example.com/missions/m001.jpg'),
(2, 'll2', 'm-002', 'Mercury Magnetospheric Boundary Mapper', 'Detailed multi-point measurements of solar wind interaction with Hermean exosphere.', 'Mercury', 'active', 'https://images.example.com/missions/m002.jpg'),
(3, 'll2', 'm-003', 'Shikoku-1 Regolith Mechanical Test', 'Testing abrasive resistance of automated excavation scoops in high-vacuum lunar environments.', 'Moon', 'completed', 'https://images.example.com/missions/m003.jpg'),
(4, 'll2', 'm-004', 'Martian Phobos Orbital Insertion', 'Establishing a stable quasi-satellite orbit around Phobos for high-resolution compositional spectroscopy.', 'Phobos', 'planned', 'https://images.example.com/missions/m004.jpg'),
(5, 'll2', 'm-005', 'Solar Corona Thermal Pulse Analyzer', 'Investigating coronal heating mechanisms and solar wind acceleration phases from the L1 Lagrange point.', 'Sun', 'active', 'https://images.example.com/missions/m005.jpg'),
(6, 'll2', 'm-006', 'Venus Atmospheric Greenhouse Dynamic Probe', 'Long-duration aerostat deployment to measure sulfuric acid droplet distribution in the middle cloud layer.', 'Venus', 'planned', 'https://images.example.com/missions/m006.jpg'),
(7, 'll2', 'm-007', 'Europa Subsurface Ocean Hydrothermal Tracer', 'Searching for chemical plume signatures escaping through the outer ice shell of Jupiter’s moon.', 'Europa', 'planned', 'https://images.example.com/missions/m007.jpg'),
(8, 'll2', 'm-008', 'Mars Gale Crater Climate Drift Study', 'Long-term meteorological monitoring using an upgraded laser-heterodyne radiometer.', 'Mars', 'completed', 'https://images.example.com/missions/m008.jpg'),
(9, 'll2', 'm-009', 'Titan Methane Lake Bathymetry Sounder', 'Deploying a floating sonar payload on Kraken Mare to map shoreline topography and depth profiles.', 'Titan', 'planned', 'https://images.example.com/missions/m009.jpg'),
(10, 'll2', 'm-010', 'Asteroid Apophis Close-Approach Radar', 'Bistatic radar imaging campaign to determine internal structural density during Earth flyby.', 'Apophis', 'failed', 'https://images.example.com/missions/m010.jpg'),
(11, 'll2', 'm-011', 'Ceres Cryovolcanic Active Site Survey', 'High-resolution imaging of Occator Crater bright spots to monitor episodic brine outgassing.', 'Ceres', 'planned', 'https://images.example.com/missions/m011.jpg'),
(12, 'll2', 'm-012', 'Enceladus Plume Organic Molecule Capture', 'Aerogel dust collector array passing through south-polar geyser plumes at hyper-velocity.', 'Enceladus', 'active', 'https://images.example.com/missions/m012.jpg'),
(13, 'll2', 'm-013', 'Deep Space Optical Comms Tech Demo', 'Testing multi-gigabit laser link reliability past the asteroid belt.', 'Deep Space', 'completed', 'https://images.example.com/missions/m013.jpg'),
(14, 'll2', 'm-014', 'Lunar South Pole Volatile Extraction', 'Pilot plant testing for thermal desorption of hydrogen and oxygen from lunar regolith.', 'Moon', 'planned', 'https://images.example.com/missions/m014.jpg'),
(15, 'll2', 'm-015', 'Mars Polar Ice Cap Stratigraphy Profiler', 'Ground-penetrating radar survey mapping ancient climate layers down to 3 kilometers depth.', 'Mars', 'planned', 'https://images.example.com/missions/m015.jpg'),
(16, 'll2', 'm-016', 'Io Volcanic Plume Plasma Torus Monitor', 'Ultraviolet spectroscopy tracking sulfur and oxygen ion dispersion across Jupiter’s magnetosphere.', 'Io', 'active', 'https://images.example.com/missions/m016.jpg'),
(17, 'll2', 'm-017', 'Comet 67P Nucleus Fracture Analysis', 'Thermal stress modeling and high-resolution optical tracking of seasonal cliff collapses.', '67P/Churyumov–Gerasimenko', 'completed', 'https://images.example.com/missions/m017.jpg'),
(18, 'll2', 'm-018', 'Geostationary Debris Removal Laser Demo', 'Evaluating ground-based pulsed laser ablation for altering defunct satellite orbits.', 'Earth orbit', 'planned', 'https://images.example.com/missions/m018.jpg'),
(19, 'll2', 'm-019', 'Venus High-Pressure Surface Lander', 'Hard-landing diagnostic capsule designed to survive 90 minutes under 92 bar atmospheric pressure.', 'Venus', 'failed', 'https://images.example.com/missions/m019.jpg'),
(20, 'll2', 'm-020', 'Mars Sample Return Earth-Return Orbiter', 'Rendezvous and orbital containment capture of sealed sample tubes originating from Jezero Crater.', 'Mars', 'planned', 'https://images.example.com/missions/m020.jpg'),
(21, 'll2', 'm-021', 'Ganymede Intrinsic Magnetic Field Mapper', 'Unraveling the unique dynamo mechanism within Jupiter’s largest moon.', 'Ganymede', 'planned', 'https://images.example.com/missions/m021.jpg'),
(22, 'll2', 'm-022', 'Saturn Ring Particle Dynamic Collisions', 'High-speed camera tracking of wave structures and moonlet wakes within the B-ring.', 'Saturn', 'active', 'https://images.example.com/missions/m022.jpg'),
(23, 'll2', 'm-023', 'Moon Far Side Radio Astronomy Array', 'Deploying low-frequency radio interferometers shielded from Earth terrestrial interference.', 'Moon', 'planned', 'https://images.example.com/missions/m023.jpg'),
(24, 'll2', 'm-024', 'Near-Earth Asteroid Redirect Technology', 'Kinetic impactor deflection test on a binary asteroid system secondary moonlet.', 'Didymos', 'completed', 'https://images.example.com/missions/m024.jpg'),
(25, 'll2', 'm-025', 'Venus Nightside Infrared Imaging', 'Mapping thermal emission anomalies to identify active tectonic rifts and basaltic flows.', 'Venus', 'planned', 'https://images.example.com/missions/m025.jpg'),
(26, 'll2', 'm-026', 'Mars Subsurface Aquifer Radar Sounding', 'Searching for liquid brines trapped within mid-latitude permafrost formations.', 'Mars', 'active', 'https://images.example.com/missions/m026.jpg'),
(27, 'll2', 'm-027', 'Jupiter Radiation Belt Hardening Test', 'Validating rad-tolerant quantum encryption modules inside intense Jovian trapped particles.', 'Jupiter', 'completed', 'https://images.example.com/missions/m027.jpg'),
(28, 'll2', 'm-028', 'Titan Aerial Autonomous Glider', 'Aero-acoustic survey of dunes and river channels in dense nitrogen atmosphere.', 'Titan', 'planned', 'https://images.example.com/missions/m028.jpg'),
(29, 'll2', 'm-029', 'Solar Polar Stereoscopic Imager', 'First-ever high-latitude stereoscopic imaging of solar coronal mass ejections.', 'Sun', 'planned', 'https://images.example.com/missions/m029.jpg'),
(30, 'll2', 'm-030', 'Lunar Dust Mitigation Electrostatic Shield', 'Testing active high-voltage repelling meshes on solar panel surfaces.', 'Moon', 'active', 'https://images.example.com/missions/m030.jpg'),
(31, 'll2', 'm-031', 'Neptune Triton Flyby Reconnaissance', 'Outer solar system gravity assist trajectory optimization and multispectral imaging.', 'Neptune', 'planned', 'https://images.example.com/missions/m031.jpg'),
(32, 'll2', 'm-032', 'Uranus Ring System In-Situ Profiler', 'Magnetic field and dust ring density measurements during equatorial plane crossing.', 'Uranus', 'planned', 'https://images.example.com/missions/m032.jpg'),
(33, 'll2', 'm-033', 'Interstellar Heliosphere Boundary Explorer', 'Measuring neutral atom charge exchange at the termination shock boundary.', 'Deep Space', 'completed', 'https://images.example.com/missions/m033.jpg'),
(34, 'll2', 'm-034', 'Mars Phobos Deimos Sample Return', 'Dual-moon landing architecture validation for multi-target sample collection.', 'Phobos', 'planned', 'https://images.example.com/missions/m034.jpg'),
(35, 'll2', 'm-035', 'Venus Phosphine Atmospheric Signature Scan', 'High-resolution Fourier transform infrared spectroscopy of trace gas components.', 'Venus', 'active', 'https://images.example.com/missions/m035.jpg'),
(36, 'll2', 'm-036', 'Asteroid Ryugu Mineralogical Mapping', 'Spectroscopic analysis of hydrated phyllosilicates and carbonaceous chondrite matrix.', 'Ryugu', 'completed', 'https://images.example.com/missions/m036.jpg'),
(37, 'll2', 'm-037', 'Asteroid Bennu Regolith Cohesion Test', 'Touch-and-go sampling mechanism performance verification on granular surfaces.', 'Bennu', 'completed', 'https://images.example.com/missions/m037.jpg'),
(38, 'll2', 'm-038', 'Moon Lava Tube Skylight Explorer', 'Hopping drone scout descending into collapsed volcanic conduits for radiation-safe habitats.', 'Moon', 'planned', 'https://images.example.com/missions/m038.jpg'),
(39, 'll2', 'm-039', 'Jupiter Trojan Asteroid Tour', 'Multi-asteroid flyby sequence targeting primitive swarms sharing Jupiter’s orbit.', 'Trojan Asteroids', 'active', 'https://images.example.com/missions/m039.jpg'),
(40, 'll2', 'm-040', 'Saturn Titan Dragonfly Relay Node', 'Communications orbiter providing continuous high-bandwidth data relay for surface rotorcraft.', 'Saturn', 'planned', 'https://images.example.com/missions/m040.jpg'),
(41, 'll2', 'm-041', 'Solar Corona Coronal Mass Ejection Tracker', 'Continuous wide-angle coronagraph observations to predict geomagnetic storm arrival times.', 'Sun', 'planned', 'https://images.example.com/missions/m041.jpg'),
(42, 'll2', 'm-042', 'Mercury Surface Mineralogy Spectrometer', 'High-resolution near-infrared mapping of volcanic plains and hollow formations.', 'Mercury', 'active', 'https://images.example.com/missions/m042.jpg'),
(43, 'll2', 'm-043', 'Venus Upper Atmosphere Plasma Sounder', 'Investigating ionospheric escape mechanisms driven by solar wind interaction.', 'Venus', 'completed', 'https://images.example.com/missions/m043.jpg'),
(44, 'll2', 'm-044', 'Moon South Pole Volatile Prospector', 'Drilling and thermal extraction analysis of subsurface hydrogen traps inside permanently shadowed craters.', 'Moon', 'planned', 'https://images.example.com/missions/m044.jpg'),
(45, 'll2', 'm-045', 'Mars Jezero Delta Sediment Core Sampler', 'Core drilling and hermetic sealing of astrobiologically promising mudstone deposits.', 'Mars', 'active', 'https://images.example.com/missions/m045.jpg'),
(46, 'll2', 'm-046', 'Jupiter Europa Radar Sounder', 'Penetrating ice-shell sounding to map brine pockets and thickness variations.', 'Europa', 'planned', 'https://images.example.com/missions/m046.jpg'),
(47, 'll2', 'm-047', 'Saturn Enceladus Thermal Plume Mapper', 'Infrared radiometry mapping active fracture zones and thermal venting.', 'Enceladus', 'completed', 'https://images.example.com/missions/m047.jpg'),
(48, 'll2', 'm-048', 'Asteroid Psyche Metallic Core Analyzer', 'Gamma-ray and neutron spectrometer mapping elemental abundances of a nickel-iron world.', 'Psyche', 'planned', 'https://images.example.com/missions/m048.jpg'),
(49, 'll2', 'm-049', 'Deep Space Gravitational Wave Pathfinder', 'Laser interferometry test bed measuring space-time ripples between free-floating test masses.', 'Deep Space', 'active', 'https://images.example.com/missions/m049.jpg'),
(50, 'll2', 'm-050', 'Titan Surface Organic Chemistry Lab', 'Gas chromatography-mass spectrometry analysis of dune sands and cryogenic liquids.', 'Titan', 'failed', 'https://images.example.com/missions/m050.jpg'),
(51, 'll2', 'm-051', 'Mars Atmosphere Volatile Evolution Observer', 'Tracking thermal escape of carbon dioxide and molecular nitrogen into space.', 'Mars', 'completed', 'https://images.example.com/missions/m051.jpg'),
(52, 'll2', 'm-052', 'Moon Geodetic Laser Altimeter', 'Precise topographic mapping of impact basins and highland relief structures.', 'Moon', 'active', 'https://images.example.com/missions/m052.jpg'),
(53, 'll2', 'm-053', 'Venus Cloud-Layer Acid Neutralizer Test', 'In-situ chemical reaction experiment testing protective coating durability in concentrated sulfuric acid.', 'Venus', 'planned', 'https://images.example.com/missions/m053.jpg'),
(54, 'll2', 'm-054', 'Jupiter Ganymede Subsurface Ocean Sounder', 'Electromagnetic sounding to characterize global liquid water layers beneath the icy crust.', 'Ganymede', 'planned', 'https://images.example.com/missions/m054.jpg'),
(55, 'll2', 'm-055', 'Saturn Ring Plane Dust Flux Monitor', 'Impact ionization detector measuring micrometeoroid bombardment rates within the main rings.', 'Saturn', 'active', 'https://images.example.com/missions/m055.jpg'),
(56, 'll2', 'm-056', 'Solar Wind Ion Composition Spectrometer', 'High-resolution mass spectrometry of coronal plasma ejected during active flare events.', 'Sun', 'completed', 'https://images.example.com/missions/m056.jpg'),
(57, 'll2', 'm-057', 'Asteroid Didymos Binary Mutual Orbit Tracker', 'Optical navigation campaign measuring subtle gravitational interactions between primary and secondary bodies.', 'Didymos', 'planned', 'https://images.example.com/missions/m057.jpg'),
(58, 'll2', 'm-058', 'Mars North Polar Dune Migration Survey', 'Time-lapse orbital stereo imaging tracking wind-driven sand transport across polar ergs.', 'Mars', 'active', 'https://images.example.com/missions/m058.jpg'),
(59, 'll2', 'm-059', 'Deep Space Interstellar Dust Collector', 'Aerogel matrix array capturing primordial cosmic dust grains entering the solar system.', 'Deep Space', 'planned', 'https://images.example.com/missions/m059.jpg'),
(60, 'll2', 'm-060', 'Jupiter Io Volcanic Vent Thermal Imager', 'High-resolution infrared monitoring of active silicate lava fountains and sulfur flows.', 'Io', 'failed', 'https://images.example.com/missions/m060.jpg'),
(61, 'll2', 'm-061', 'Moon Orientale Basin Gravity Mapper', 'Precise Doppler tracking of spacecraft acceleration to map subsurface mascon structures.', 'Moon', 'completed', 'https://images.example.com/missions/m061.jpg'),
(62, 'll2', 'm-062', 'Venus Express Thermal Structure Profiler', 'Radio occultation sounding measuring vertical temperature and pressure gradients.', 'Venus', 'active', 'https://images.example.com/missions/m062.jpg'),
(63, 'll2', 'm-063', 'Mars Aeolis Palus Rover Navigation Test', 'Autonomous hazard detection and pathfinding performance verification on rugged terrain.', 'Mars', 'completed', 'https://images.example.com/missions/m063.jpg'),
(64, 'll2', 'm-064', 'Saturn Titan Hydrocarbon Lake Sounder', 'Active radar reflection profiling measuring liquid methane and ethane turbidity.', 'Titan', 'planned', 'https://images.example.com/missions/m064.jpg'),
(65, 'll2', 'm-065', 'Jupiter Radiation Environment Characterization', 'High-energy electron and proton flux monitoring for future crewed electronic shielding designs.', 'Jupiter', 'active', 'https://images.example.com/missions/m065.jpg'),
(66, 'll2', 'm-066', 'Asteroid Apophis Yarkovsky Effect Analyzer', 'Laser range-finding tracking thermal radiation recoil forces altering orbital trajectory.', 'Apophis', 'planned', 'https://images.example.com/missions/m066.jpg'),
(67, 'll2', 'm-067', 'Solar Heliospheric Boundary Neutral Atom Imager', 'Remote sensing of energetic neutral atoms streaming back from the heliopause.', 'Deep Space', 'completed', 'https://images.example.com/missions/m067.jpg'),
(68, 'll2', 'm-068', 'Mars Isidis Planitia Mineral Survey', 'Multispectral thermal emission analysis of clay-bearing alluvial fan deposits.', 'Mars', 'planned', 'https://images.example.com/missions/m068.jpg'),
(69, 'll2', 'm-069', 'Moon Aristarchus Plateau Volcanic Mapper', 'High-resolution optical mapping of pyroclastic dark mantle deposits and glass beads.', 'Moon', 'active', 'https://images.example.com/missions/m069.jpg'),
(70, 'll2', 'm-070', 'Europa Ice Shell Mechanical Stress Tester', 'Long-term seismic monitoring of tidal flexing and cracking phenomena.', 'Europa', 'planned', 'https://images.example.com/missions/m070.jpg'),
(71, 'll2', 'm-071', 'Venus High-Altitude Aerobot Science Lab', 'Buoyant platform drifting for 30 days in temperate cloud layers at 55 kilometers altitude.', 'Venus', 'planned', 'https://images.example.com/missions/m071.jpg'),
(72, 'll2', 'm-072', 'Saturn Mimas Ocean Hypothesis Test', 'Libration and rotational dynamics measurement to detect hidden internal liquid water oceans.', 'Mimas', 'active', 'https://images.example.com/missions/m072.jpg'),
(73, 'll2', 'm-073', 'Mars South Polar Residual Ice Mapper', 'Subsurface radar sounding quantifying carbon dioxide ice volume and recession rates.', 'Mars', 'completed', 'https://images.example.com/missions/m073.jpg'),
(74, 'll2', 'm-074', 'Jupiter Callisto Ancient Crater Topography', 'Multispectral stereo mapping of heavily cratered, tectonically inactive terrain.', 'Callisto', 'planned', 'https://images.example.com/missions/m074.jpg'),
(75, 'll2', 'm-075', 'Deep Space Optical Time Transfer Demo', 'Sub-nanosecond clock synchronization validation across interplanetary distances.', 'Deep Space', 'active', 'https://images.example.com/missions/m075.jpg'),
(76, 'll2', 'm-076', 'Moon South Pole Illumination Topography', 'High-resolution digital elevation modeling of peaks of eternal light and deep shadows.', 'Moon', 'completed', 'https://images.example.com/missions/m076.jpg'),
(77, 'll2', 'm-077', 'Asteroid Ryugu Spin Axis Dynamics', 'YORP effect measurement via precise optical tracking of small surface landmarks.', 'Ryugu', 'completed', 'https://images.example.com/missions/m077.jpg'),
(78, 'll2', 'm-078', 'Mars Acidalia Planitia Plain Lander', 'Meteorological station and soil moisture sensor network deployment.', 'Mars', 'failed', 'https://images.example.com/missions/m078.jpg'),
(79, 'll2', 'm-079', 'Saturn Ring F-Ring Shepherd Moon Monitor', 'High-resolution imaging of complex strand braiding and gravitational perturbations.', 'Saturn', 'planned', 'https://images.example.com/missions/m079.jpg'),
(80, 'll2', 'm-080', 'Solar Inner Corona Plasma Polarimeter', 'Polarimetric imaging of electron density fluctuations close to the solar limb.', 'Sun', 'active', 'https://images.example.com/missions/m080.jpg'),
(81, 'll2', 'm-081', 'Venus Nightside Oxygen Airglow Mapper', 'Mapping upper atmospheric circulation patterns via near-infrared hydroxyl and oxygen emissions.', 'Venus', 'planned', 'https://images.example.com/missions/m081.jpg'),
(82, 'll2', 'm-082', 'Jupiter Magnetotail Plasma Sheet Profiler', 'In-situ energetic particle detection in the distant Jovian magnetic wake.', 'Jupiter', 'completed', 'https://images.example.com/missions/m082.jpg'),
(83, 'll2', 'm-083', 'Moon Reiner Gamma Magnetic Anomaly Scout', 'Low-altitude surface magnetic field mapping of swirl-like albedo formations.', 'Moon', 'active', 'https://images.example.com/missions/m083.jpg'),
(84, 'll2', 'm-084', 'Mars Valles Marineris Canyon Wall Profiler', 'Descent imaging and spectroscopic profiling of exposed ancient geological strata.', 'Mars', 'planned', 'https://images.example.com/missions/m084.jpg'),
(85, 'll2', 'm-085', 'Titan Shangri-La Dune Field Radar', 'Synthetic aperture radar mapping of longitudinal sand dunes and inter-dune spacing.', 'Titan', 'active', 'https://images.example.com/missions/m085.jpg'),
(86, 'll2', 'm-086', 'Asteroid Bennu Particle Ejection Monitor', 'Long-term optical monitoring of spontaneous gravel and dust particle liftoff events.', 'Bennu', 'completed', 'https://images.example.com/missions/m086.jpg'),
(87, 'll2', 'm-087', 'Deep Space Solar Sail Propulsion Demo', 'Large-area reflective membrane deployment and photon pressure trajectory control.', 'Deep Space', 'planned', 'https://images.example.com/missions/m087.jpg'),
(88, 'll2', 'm-088', 'Mars Utopia Planitia Ice Table Survey', 'Shallow subsurface radar profiling of buried glacial ice sheets.', 'Mars', 'active', 'https://images.example.com/missions/m088.jpg'),
(89, 'll2', 'm-089', 'Saturn D-Ring Inner Structure Imager', 'High-sensitivity optical observations of faint innermost ring dynamics.', 'Saturn', 'planned', 'https://images.example.com/missions/m089.jpg'),
(90, 'll2', 'm-090', 'Jupiter Amalthea Orbit Reconnaissance', 'Close-range gravity and shape measurements of an inner irregular moon.', 'Jupiter', 'completed', 'https://images.example.com/missions/m090.jpg'),
(91, 'll2', 'm-091', 'Moon Schrodinger Basin Peak Ring Lander', 'Geological exploration and sample collection from deep crustal impact excavation sites.', 'Moon', 'planned', 'https://images.example.com/missions/m091.jpg'),
(92, 'll2', 'm-092', 'Venus Volcanic Eruption Thermal Monitor', 'Global surveillance of transient infrared hotspots indicating active basaltic volcanism.', 'Venus', 'active', 'https://images.example.com/missions/m092.jpg'),
(93, 'll2', 'm-093', 'Mars Orbital Communications Relay Node', 'High-bandwidth UHF and Ka-band data forwarding for surface rovers and landers.', 'Mars', 'active', 'https://images.example.com/missions/m093.jpg'),
(94, 'll2', 'm-094', 'Saturn Iapetus Albedo Boundary Mapper', 'Multispectral analysis of the stark two-tone coloration dividing leading and trailing hemispheres.', 'Iapetus', 'completed', 'https://images.example.com/missions/m094.jpg'),
(95, 'll2', 'm-095', 'Solar Polar Magnetic Field Inversion Scout', 'High-latitude heliospheric measurement of polar magnetic field reversal dynamics.', 'Sun', 'planned', 'https://images.example.com/missions/m095.jpg'),
(96, 'll2', 'm-096', 'Asteroid Toutatis Close-Approach Radar', 'Bistatic radar ranging and shape reconstruction during Earth intersection trajectory.', 'Toutatis', 'completed', 'https://images.example.com/missions/m096.jpg'),
(97, 'll2', 'm-097', 'Jupiter Europa Lander Biological Analyzer', 'Sub-surface ice melting and fluorescence microscope detection of extant amino acids.', 'Europa', 'planned', 'https://images.example.com/missions/m097.jpg'),
(98, 'll2', 'm-098', 'Moon Mare Tranquillitatis Geodetic Beacon', 'Laser retroreflector array placement for millimeter-precision Earth-Moon distance monitoring.', 'Moon', 'completed', 'https://images.example.com/missions/m098.jpg'),
(99, 'll2', 'm-099', 'Mars Olympus Mons Aureole Structure Imager', 'High-resolution stereo mapping of massive landslide deposits surrounding shield volcano flanks.', 'Mars', 'active', 'https://images.example.com/missions/m099.jpg'),
(100, 'll2', 'm-100', 'Deep Space Kuiper Belt Object Flyby Scout', 'Long-duration nuclear-powered reconnaissance of primitive trans-Neptunian planetoids.', 'Deep Space', 'planned', 'https://images.example.com/missions/m100.jpg');

-- =========================================================================
-- 5. Junction Table: Mission Agencies (0 to 2 Agencies per Mission)
-- =========================================================================
INSERT INTO mission_agencies (mission_id, agency_id, role) VALUES
(1, 1, 'Primary'), (1, 3, 'Contributor'),
(2, 2, 'Primary'),
(3, 3, 'Primary'),
(4, 4, 'Primary'), (4, 1, 'Contributor'),
(5, 5, 'Primary'),
(6, 1, 'Primary'),
(7, 2, 'Primary'), (7, 4, 'Contributor'),
(8, 3, 'Primary'),
(9, 4, 'Primary'),
(10, 5, 'Primary'), (10, 1, 'Contributor'),
(11, 1, 'Primary'),
(12, 2, 'Primary'), (12, 3, 'Contributor'),
(13, 3, 'Primary'),
(14, 4, 'Primary'),
(15, 5, 'Primary'), (15, 2, 'Contributor'),
(16, 1, 'Primary'),
(17, 2, 'Primary'),
(18, 3, 'Primary'), (18, 4, 'Contributor'),
(19, 4, 'Primary'),
(20, 5, 'Primary'),
(21, 1, 'Primary'), (21, 2, 'Contributor'),
(22, 2, 'Primary'),
(23, 3, 'Primary'),
(24, 4, 'Primary'), (24, 5, 'Contributor'),
(25, 5, 'Primary'),
(26, 1, 'Primary'),
(27, 2, 'Primary'), (27, 3, 'Contributor'),
(28, 3, 'Primary'),
(29, 4, 'Primary'),
(30, 5, 'Primary'), (30, 1, 'Contributor'),
(31, 1, 'Primary'),
(32, 2, 'Primary'), (32, 4, 'Contributor'),
(33, 3, 'Primary'),
(34, 4, 'Primary'),
(35, 5, 'Primary'), (35, 2, 'Contributor'),
(36, 1, 'Primary'),
(37, 2, 'Primary'),
(38, 3, 'Primary'), (38, 5, 'Contributor'),
(39, 4, 'Primary'),
(40, 5, 'Primary'),
(41, 1, 'Primary'), (41, 3, 'Contributor'),
(42, 2, 'Primary'),
(43, 3, 'Primary'),
(44, 4, 'Primary'), (44, 1, 'Contributor'),
(45, 5, 'Primary'),
(46, 1, 'Primary'),
(47, 2, 'Primary'), (47, 4, 'Contributor'),
(48, 3, 'Primary'),
(49, 4, 'Primary'),
(50, 5, 'Primary'), (50, 2, 'Contributor'),
(51, 1, 'Primary'),
(52, 2, 'Primary'), (52, 3, 'Contributor'),
(53, 3, 'Primary'),
(54, 4, 'Primary'),
(55, 5, 'Primary'), (55, 1, 'Contributor'),
(56, 1, 'Primary'),
(57, 2, 'Primary'),
(58, 3, 'Primary'), (58, 4, 'Contributor'),
(59, 4, 'Primary'),
(60, 5, 'Primary'),
(61, 1, 'Primary'), (61, 2, 'Contributor'),
(62, 2, 'Primary'),
(63, 3, 'Primary'),
(64, 4, 'Primary'), (64, 5, 'Contributor'),
(65, 5, 'Primary'),
(66, 1, 'Primary'),
(67, 2, 'Primary'), (67, 3, 'Contributor'),
(68, 3, 'Primary'),
(69, 4, 'Primary'),
(70, 5, 'Primary'), (70, 1, 'Contributor'),
(71, 1, 'Primary'),
(72, 2, 'Primary'), (72, 4, 'Contributor'),
(73, 3, 'Primary'),
(74, 4, 'Primary'),
(75, 5, 'Primary'), (75, 2, 'Contributor'),
(76, 1, 'Primary'),
(77, 2, 'Primary'),
(78, 3, 'Primary'), (78, 5, 'Contributor'),
(79, 4, 'Primary'),
(80, 5, 'Primary'),
(81, 1, 'Primary'), (81, 3, 'Contributor'),
(82, 2, 'Primary'),
(83, 3, 'Primary'),
(84, 4, 'Primary'), (84, 1, 'Contributor'),
(85, 5, 'Primary'),
(86, 1, 'Primary'),
(87, 2, 'Primary'), (87, 4, 'Contributor'),
(88, 3, 'Primary'),
(89, 4, 'Primary'),
(90, 5, 'Primary'), (90, 2, 'Contributor'),
(91, 1, 'Primary'),
(92, 2, 'Primary'), (92, 3, 'Contributor'),
(93, 3, 'Primary'),
(94, 4, 'Primary'),
(95, 5, 'Primary'), (95, 1, 'Contributor'),
(96, 1, 'Primary'),
(97, 2, 'Primary'),
(98, 3, 'Primary'), (98, 4, 'Contributor'),
(99, 4, 'Primary'),
(100, 5, 'Primary');

-- =========================================================================
-- 6. Junction Table: Mission Spacecraft (0 to 3 Spacecraft per Mission)
-- =========================================================================
INSERT INTO mission_spacecraft (mission_id, spacecraft_id) VALUES
(1, 101), (1, 103),
(2, 102),
(3, 103), (3, 105),
(4, 104),
(5, 105), (5, 101), (5, 102),
(6, 106),
(7, 107), (7, 108),
(8, 109),
(9, 110), (9, 111),
(10, 112),
(11, 113), (11, 114),
(12, 115),
(13, 116), (13, 117), (13, 118),
(14, 119),
(15, 120),
(16, 121), (16, 122),
(17, 123),
(18, 124), (18, 125),
(19, 126),
(20, 127), (20, 128), (20, 129),
(21, 130),
(22, 131), (22, 132),
(23, 133),
(24, 134), (24, 135),
(25, 136),
(26, 137), (26, 138), (26, 139),
(27, 140),
(28, 141), (28, 142),
(29, 143),
(30, 144), (30, 145), (30, 146),
(31, 147),
(32, 148),
(33, 149), (33, 150),
(34, 151),
(35, 152), (35, 153), (35, 154),
(36, 155),
(37, 156),
(38, 157), (38, 158),
(39, 159),
(40, 160), (40, 161), (40, 162),
(41, 163),
(42, 164), (42, 165),
(43, 166),
(44, 167), (44, 168),
(45, 169),
(46, 170), (46, 171), (46, 172),
(47, 173),
(48, 174), (48, 175),
(49, 176),
(50, 177), (50, 178), (50, 179),
(51, 180),
(52, 181), (52, 182),
(53, 183),
(54, 184), (54, 185),
(55, 186),
(56, 187), (56, 188), (56, 189),
(57, 190),
(58, 191), (58, 192),
(59, 193),
(60, 194), (60, 195), (60, 196),
(61, 197),
(62, 198), (62, 199),
(63, 200),
(64, 201), (64, 202),
(65, 203),
(66, 204), (66, 205), (66, 206),
(67, 207),
(68, 208), (68, 209),
(69, 210),
(70, 211), (70, 212), (70, 213),
(71, 214),
(72, 215), (72, 216),
(73, 217),
(74, 218), (74, 219),
(75, 220),
(76, 221), (76, 222), (76, 223),
(77, 224),
(78, 225), (78, 226),
(79, 227),
(80, 228), (80, 229), (80, 230),
(81, 231),
(82, 232), (82, 233),
(83, 234),
(84, 235), (84, 236),
(85, 237),
(86, 238), (86, 239), (86, 240),
(87, 241),
(88, 242), (88, 243),
(89, 244),
(90, 245), (90, 246), (90, 247),
(91, 248),
(92, 249), (92, 250),
(93, 101),
(94, 105), (94, 110),
(95, 115),
(96, 120), (96, 125), (96, 130),
(97, 135),
(98, 140), (98, 145),
(99, 150),
(100, 155), (100, 160), (100, 165);

-- =========================================================================
-- 7. Junction Table: Mission Launches (Ensuring launch_id 1 to 20 are all used)
-- =========================================================================
INSERT INTO mission_launches (mission_id, launch_id) VALUES
-- Map launch_id 1 to 20 to missions 1 to 20 respectively to prevent isolation
(1, 1), (2, 2), (3, 3), (4, 4), (5, 5),
(6, 6), (7, 7), (8, 8), (9, 9), (10, 10),
(11, 11), (12, 12), (13, 13), (14, 14), (15, 15),
(16, 16), (17, 17), (18, 18), (19, 19), (20, 20),

-- Distribute launch associations across remaining missions 21 to 100
(21, 1), (22, 2), (23, 3), (24, 4), (25, 5),
(26, 6), (27, 7), (28, 8), (29, 9), (30, 10),
(31, 11), (32, 12), (33, 13), (34, 14), (35, 15),
(36, 16), (37, 17), (38, 18), (39, 19), (40, 20),
(41, 1), (42, 2), (43, 3), (44, 4), (45, 5),
(46, 6), (47, 7), (48, 8), (49, 9), (50, 10),
(51, 11), (52, 12), (53, 13), (54, 14), (55, 15),
(56, 16), (57, 17), (58, 18), (59, 19), (60, 20),
(61, 1), (62, 2), (63, 3), (64, 4), (65, 5),
(66, 6), (67, 7), (68, 8), (69, 9), (70, 10),
(71, 11), (72, 12), (73, 13), (74, 14), (75, 15),
(76, 16), (77, 17), (78, 18), (79, 19), (80, 20),
(81, 1), (82, 2), (83, 3), (84, 4), (85, 5),
(86, 6), (87, 7), (88, 8), (89, 9), (90, 10),
(91, 11), (92, 12), (93, 13), (94, 14), (95, 15),
(96, 16), (97, 17), (98, 18), (99, 19), (100, 20);

COMMIT;
