mysql -h 127.0.0.1 -P 3306 -u root -p
CREATE USER IF NOT EXISTS 'crkl'@'127.0.0.1' IDENTIFIED BY 'REPLACE_WITH_A_STRONG_PASSWORD';
ALTER USER 'crkl'@'127.0.0.1' IDENTIFIED BY 'REPLACE_WITH_A_STRONG_PASSWORD';
GRANT SELECT, INSERT, UPDATE, DELETE ON crkl_db.* TO 'crkl'@'127.0.0.1';
ALTER USER 'crkl'@'localhost' IDENTIFIED BY 'REPLACE_WITH_A_STRONG_PASSWORD';
GRANT SELECT, INSERT, UPDATE, DELETE ON crkl_db.* TO 'crkl'@'localhost';
FLUSH PRIVILEGES;
