-- Deterministic dummy data for space_exploration_db
-- Requires schema.md to be applied first.
-- The 10 source rows are required because organizations.source_id is also a foreign key.

USE space_exploration_db;

START TRANSACTION;

-- Ten source records: two primary sources and eight organization source records.
INSERT INTO sources (source_id, name, base_url, api_endpoint, source_type, is_active) VALUES
    (1, 'NASA Data Portal', 'https://data.nasa.gov', 'https://api.nasa.gov', 'organization', TRUE),
    (2, 'ESA Open Data', 'https://data.esa.int', 'https://api.esa.int', 'organization', TRUE),
    (3, 'Organization 01 Data Source', 'https://org01.space.example', 'https://org01.space.example/api', 'organization', TRUE),
    (4, 'Organization 02 Data Source', 'https://org02.space.example', 'https://org02.space.example/api', 'organization', TRUE),
    (5, 'Organization 03 Data Source', 'https://org03.space.example', 'https://org03.space.example/api', 'organization', TRUE),
    (6, 'Organization 04 Data Source', 'https://org04.space.example', 'https://org04.space.example/api', 'organization', TRUE),
    (7, 'Organization 05 Data Source', 'https://org05.space.example', 'https://org05.space.example/api', 'organization', TRUE),
    (8, 'Organization 06 Data Source', 'https://org06.space.example', 'https://org06.space.example/api', 'organization', TRUE),
    (9, 'Organization 07 Data Source', 'https://org07.space.example', 'https://org07.space.example/api', 'organization', TRUE),
    (10, 'Organization 08 Data Source', 'https://org08.space.example', 'https://org08.space.example/api', 'organization', TRUE);

-- Ten organizations, each extending one source record.
INSERT INTO organizations (source_id, country_code, org_type, established_year) VALUES
    (1, 'USA', 'government_agency', 1963),
    (2, 'FRA', 'government_agency', 1968),
    (3, 'JPN', 'commercial_company', 1973),
    (4, 'DEU', 'research_institute', 1978),
    (5, 'CAN', 'non_profit', 1983),
    (6, 'INT', 'international_body', 1988),
    (7, 'IND', 'commercial_company', 1993),
    (8, 'GBR', 'research_institute', 1998),
    (9, 'AUS', 'government_agency', 2003),
    (10, 'ITA', 'non_profit', 2008);

-- One hundred missions with descriptive detail.
INSERT INTO missions (mission_id, org_source_id, name, description, target_body, status, launched_at) VALUES
    (1, 1, 'Lunar Ice Mapper', 'Lunar Ice Mapper is carrying out a focused campaign to map permanently shadowed craters for water ice. The mission combines remote sensing, onboard analysis, and autonomous operations to improve understanding of the Moon.', 'Moon', 'planned', NULL),
    (2, 2, 'Artemis Ridge Surveyor', 'Artemis Ridge Surveyor is carrying out a focused campaign to collect mineral samples from an ancient river delta. The mission combines remote sensing, onboard analysis, and autonomous operations to improve understanding of Mars.', 'Mars', 'active', '2011-02-02 12:00:00'),
    (3, 3, 'Selene Seismic Network', 'Selene Seismic Network completed a focused campaign to measure changes in the upper atmosphere and ionosphere. Its results support comparative studies of Earth orbit and help refine designs for future exploration systems.', 'Earth orbit', 'completed', '2012-03-03 12:00:00'),
    (4, 4, 'Lunar Horizon Pathfinder', 'Lunar Horizon Pathfinder attempted to test instrumentation designed to survive extreme thermal conditions, but the campaign ended before all objectives were met. The engineering data remains valuable for improving reliability in future Venus missions.', 'Venus', 'failed', '2013-04-04 12:00:00'),
    (5, 5, 'CraterLight Explorer', 'CraterLight Explorer is carrying out a focused campaign to measure the planet''''s magnetic field and radiation environment. The mission combines remote sensing, onboard analysis, and autonomous operations to improve understanding of Jupiter.', 'Jupiter', 'planned', NULL),
    (6, 6, 'Regolith Navigator', 'Regolith Navigator is carrying out a focused campaign to study atmospheric circulation and polar storm activity. The mission combines remote sensing, onboard analysis, and autonomous operations to improve understanding of Saturn.', 'Saturn', 'active', '2015-06-06 12:00:00'),
    (7, 7, 'Moonwatch Relay', 'Moonwatch Relay completed a focused campaign to search for hydrated minerals and evidence of past alteration. Its results support comparative studies of the asteroid belt and help refine designs for future exploration systems.', 'Asteroid belt', 'completed', '2016-07-07 12:00:00'),
    (8, 8, 'Polar Beacon', 'Polar Beacon attempted to measure the moon''''s induced magnetic field, but the campaign ended before all objectives were met. The engineering data remains valuable for improving reliability in future Europa missions.', 'Europa', 'failed', '2017-08-08 12:00:00'),
    (9, 9, 'Lunar Prospector II', 'Lunar Prospector II is carrying out a focused campaign to study methane-based weather cycles and surface lakes. The mission combines remote sensing, onboard analysis, and autonomous operations to improve understanding of Titan.', 'Titan', 'planned', NULL),
    (10, 10, 'Cislunar Gateway Scout', 'Cislunar Gateway Scout is carrying out a focused campaign to measure the local interstellar environment. The mission combines remote sensing, onboard analysis, and autonomous operations to improve understanding of deep space.', 'Deep space', 'active', '2019-10-10 12:00:00'),
    (11, 1, 'Ares Delta Survey', 'Ares Delta Survey completed a focused campaign to deploy a compact seismic network to study the lunar interior. Its results support comparative studies of the Moon and help refine designs for future exploration systems.', 'Moon', 'completed', '2020-11-11 12:00:00'),
    (12, 2, 'Red Mesa Pathfinder', 'Red Mesa Pathfinder attempted to evaluate technologies for a future sample-return campaign, but the campaign ended before all objectives were met. The engineering data remains valuable for improving reliability in future Mars missions.', 'Mars', 'failed', '2021-12-12 12:00:00'),
    (13, 3, 'Olympus Climate Orbiter', 'Olympus Climate Orbiter is carrying out a focused campaign to observe ocean temperatures and long-term climate indicators. The mission combines remote sensing, onboard analysis, and autonomous operations to improve understanding of Earth orbit.', 'Earth orbit', 'planned', NULL),
    (14, 4, 'Mars Sample Scout', 'Mars Sample Scout is carrying out a focused campaign to map volcanic features beneath the dense atmosphere. The mission combines remote sensing, onboard analysis, and autonomous operations to improve understanding of Venus.', 'Venus', 'active', '2023-02-14 12:00:00'),
    (15, 5, 'Valles Explorer', 'Valles Explorer completed a focused campaign to investigate the interaction between the solar wind and the magnetosphere. Its results support comparative studies of Jupiter and help refine designs for future exploration systems.', 'Jupiter', 'completed', '2024-03-15 12:00:00'),
    (16, 6, 'Dustwatch Relay', 'Dustwatch Relay attempted to refine models of the Saturnian magnetosphere, but the campaign ended before all objectives were met. The engineering data remains valuable for improving reliability in future Saturn missions.', 'Saturn', 'failed', '2025-04-16 12:00:00'),
    (17, 7, 'Hellas Basin Mapper', 'Hellas Basin Mapper is carrying out a focused campaign to determine the composition of a primitive carbon-rich asteroid. The mission combines remote sensing, onboard analysis, and autonomous operations to improve understanding of the asteroid belt.', 'Asteroid belt', 'planned', NULL),
    (18, 8, 'Phobos Approach', 'Phobos Approach is carrying out a focused campaign to search for plume activity and organic compounds. The mission combines remote sensing, onboard analysis, and autonomous operations to improve understanding of Europa.', 'Europa', 'active', '2011-06-18 12:00:00'),
    (19, 9, 'Aurora Mars Network', 'Aurora Mars Network completed a focused campaign to map the distribution of dunes and river channels. Its results support comparative studies of Titan and help refine designs for future exploration systems.', 'Titan', 'completed', '2012-07-19 12:00:00'),
    (20, 10, 'Red Planet Geochemist', 'Red Planet Geochemist attempted to search for transient objects and unexplained high-energy events, but the campaign ended before all objectives were met. The engineering data remains valuable for improving reliability in future deep space missions.', 'Deep space', 'failed', '2013-08-20 12:00:00'),
    (21, 1, 'TerraWatch Climate', 'TerraWatch Climate is carrying out a focused campaign to map permanently shadowed craters for water ice. The mission combines remote sensing, onboard analysis, and autonomous operations to improve understanding of the Moon.', 'Moon', 'planned', NULL),
    (22, 2, 'Ocean Sentinel', 'Ocean Sentinel is carrying out a focused campaign to collect mineral samples from an ancient river delta. The mission combines remote sensing, onboard analysis, and autonomous operations to improve understanding of Mars.', 'Mars', 'active', '2015-10-22 12:00:00'),
    (23, 3, 'Ionosphere Mapper', 'Ionosphere Mapper completed a focused campaign to measure changes in the upper atmosphere and ionosphere. Its results support comparative studies of Earth orbit and help refine designs for future exploration systems.', 'Earth orbit', 'completed', '2016-11-23 12:00:00'),
    (24, 4, 'DisasterEye Pathfinder', 'DisasterEye Pathfinder attempted to test instrumentation designed to survive extreme thermal conditions, but the campaign ended before all objectives were met. The engineering data remains valuable for improving reliability in future Venus missions.', 'Venus', 'failed', '2017-12-24 12:00:00'),
    (25, 5, 'Atmosphere Link', 'Atmosphere Link is carrying out a focused campaign to measure the planet''''s magnetic field and radiation environment. The mission combines remote sensing, onboard analysis, and autonomous operations to improve understanding of Jupiter.', 'Jupiter', 'planned', NULL),
    (26, 6, 'Aurora Monitor', 'Aurora Monitor is carrying out a focused campaign to study atmospheric circulation and polar storm activity. The mission combines remote sensing, onboard analysis, and autonomous operations to improve understanding of Saturn.', 'Saturn', 'active', '2019-02-26 12:00:00'),
    (27, 7, 'EarthLoom Observatory', 'EarthLoom Observatory completed a focused campaign to search for hydrated minerals and evidence of past alteration. Its results support comparative studies of the asteroid belt and help refine designs for future exploration systems.', 'Asteroid belt', 'completed', '2020-03-27 12:00:00'),
    (28, 8, 'Coastal Scan', 'Coastal Scan attempted to measure the moon''''s induced magnetic field, but the campaign ended before all objectives were met. The engineering data remains valuable for improving reliability in future Europa missions.', 'Europa', 'failed', '2021-04-01 12:00:00'),
    (29, 9, 'GeoPulse', 'GeoPulse is carrying out a focused campaign to study methane-based weather cycles and surface lakes. The mission combines remote sensing, onboard analysis, and autonomous operations to improve understanding of Titan.', 'Titan', 'planned', NULL),
    (30, 10, 'Orbiting Climate Lab', 'Orbiting Climate Lab is carrying out a focused campaign to measure the local interstellar environment. The mission combines remote sensing, onboard analysis, and autonomous operations to improve understanding of deep space.', 'Deep space', 'active', '2023-06-03 12:00:00'),
    (31, 1, 'Aphrodite Cloud Probe', 'Aphrodite Cloud Probe completed a focused campaign to deploy a compact seismic network to study the lunar interior. Its results support comparative studies of the Moon and help refine designs for future exploration systems.', 'Moon', 'completed', '2024-07-04 12:00:00'),
    (32, 2, 'Venus Crest Mapper', 'Venus Crest Mapper attempted to evaluate technologies for a future sample-return campaign, but the campaign ended before all objectives were met. The engineering data remains valuable for improving reliability in future Mars missions.', 'Mars', 'failed', '2025-08-05 12:00:00'),
    (33, 3, 'Morning Star Orbiter', 'Morning Star Orbiter is carrying out a focused campaign to observe ocean temperatures and long-term climate indicators. The mission combines remote sensing, onboard analysis, and autonomous operations to improve understanding of Earth orbit.', 'Earth orbit', 'planned', NULL),
    (34, 4, 'Ishtar Atmospheric Lab', 'Ishtar Atmospheric Lab is carrying out a focused campaign to map volcanic features beneath the dense atmosphere. The mission combines remote sensing, onboard analysis, and autonomous operations to improve understanding of Venus.', 'Venus', 'active', '2011-10-07 12:00:00'),
    (35, 5, 'Venus Aerobrake Demo', 'Venus Aerobrake Demo completed a focused campaign to investigate the interaction between the solar wind and the magnetosphere. Its results support comparative studies of Jupiter and help refine designs for future exploration systems.', 'Jupiter', 'completed', '2012-11-08 12:00:00'),
    (36, 6, 'Cloudveil Explorer', 'Cloudveil Explorer attempted to refine models of the Saturnian magnetosphere, but the campaign ended before all objectives were met. The engineering data remains valuable for improving reliability in future Saturn missions.', 'Saturn', 'failed', '2013-12-09 12:00:00'),
    (37, 7, 'Corona Radar Survey', 'Corona Radar Survey is carrying out a focused campaign to determine the composition of a primitive carbon-rich asteroid. The mission combines remote sensing, onboard analysis, and autonomous operations to improve understanding of the asteroid belt.', 'Asteroid belt', 'planned', NULL),
    (38, 8, 'Inferno Chemistry Probe', 'Inferno Chemistry Probe is carrying out a focused campaign to search for plume activity and organic compounds. The mission combines remote sensing, onboard analysis, and autonomous operations to improve understanding of Europa.', 'Europa', 'active', '2015-02-11 12:00:00'),
    (39, 9, 'Venus Windwatch', 'Venus Windwatch completed a focused campaign to map the distribution of dunes and river channels. Its results support comparative studies of Titan and help refine designs for future exploration systems.', 'Titan', 'completed', '2016-03-12 12:00:00'),
    (40, 10, 'Hesperus Pathfinder', 'Hesperus Pathfinder attempted to search for transient objects and unexplained high-energy events, but the campaign ended before all objectives were met. The engineering data remains valuable for improving reliability in future deep space missions.', 'Deep space', 'failed', '2017-04-13 12:00:00'),
    (41, 1, 'Jovian Magnetometer', 'Jovian Magnetometer is carrying out a focused campaign to map permanently shadowed craters for water ice. The mission combines remote sensing, onboard analysis, and autonomous operations to improve understanding of the Moon.', 'Moon', 'planned', NULL),
    (42, 2, 'Great Red Spot Watch', 'Great Red Spot Watch is carrying out a focused campaign to collect mineral samples from an ancient river delta. The mission combines remote sensing, onboard analysis, and autonomous operations to improve understanding of Mars.', 'Mars', 'active', '2019-06-15 12:00:00'),
    (43, 3, 'Europa System Surveyor', 'Europa System Surveyor completed a focused campaign to measure changes in the upper atmosphere and ionosphere. Its results support comparative studies of Earth orbit and help refine designs for future exploration systems.', 'Earth orbit', 'completed', '2020-07-16 12:00:00'),
    (44, 4, 'Jupiter Aurora Explorer', 'Jupiter Aurora Explorer attempted to test instrumentation designed to survive extreme thermal conditions, but the campaign ended before all objectives were met. The engineering data remains valuable for improving reliability in future Venus missions.', 'Venus', 'failed', '2021-08-17 12:00:00'),
    (45, 5, 'Galilean Context Orbiter', 'Galilean Context Orbiter is carrying out a focused campaign to measure the planet''''s magnetic field and radiation environment. The mission combines remote sensing, onboard analysis, and autonomous operations to improve understanding of Jupiter.', 'Jupiter', 'planned', NULL),
    (46, 6, 'Storm Lantern', 'Storm Lantern is carrying out a focused campaign to study atmospheric circulation and polar storm activity. The mission combines remote sensing, onboard analysis, and autonomous operations to improve understanding of Saturn.', 'Saturn', 'active', '2023-10-19 12:00:00'),
    (47, 7, 'Jovian Radiation Lab', 'Jovian Radiation Lab completed a focused campaign to search for hydrated minerals and evidence of past alteration. Its results support comparative studies of the asteroid belt and help refine designs for future exploration systems.', 'Asteroid belt', 'completed', '2024-11-20 12:00:00'),
    (48, 8, 'Io Plasma Monitor', 'Io Plasma Monitor attempted to measure the moon''''s induced magnetic field, but the campaign ended before all objectives were met. The engineering data remains valuable for improving reliability in future Europa missions.', 'Europa', 'failed', '2025-12-21 12:00:00'),
    (49, 9, 'Zeus Deep Survey', 'Zeus Deep Survey is carrying out a focused campaign to study methane-based weather cycles and surface lakes. The mission combines remote sensing, onboard analysis, and autonomous operations to improve understanding of Titan.', 'Titan', 'planned', NULL),
    (50, 10, 'Jupiter Frontier Scout', 'Jupiter Frontier Scout is carrying out a focused campaign to measure the local interstellar environment. The mission combines remote sensing, onboard analysis, and autonomous operations to improve understanding of deep space.', 'Deep space', 'active', '2011-02-23 12:00:00'),
    (51, 1, 'Saturn Ring Surveyor', 'Saturn Ring Surveyor completed a focused campaign to deploy a compact seismic network to study the lunar interior. Its results support comparative studies of the Moon and help refine designs for future exploration systems.', 'Moon', 'completed', '2012-03-24 12:00:00'),
    (52, 2, 'Titan Weather Watch', 'Titan Weather Watch attempted to evaluate technologies for a future sample-return campaign, but the campaign ended before all objectives were met. The engineering data remains valuable for improving reliability in future Mars missions.', 'Mars', 'failed', '2013-04-25 12:00:00'),
    (53, 3, 'Chronos Atmospheric Lab', 'Chronos Atmospheric Lab is carrying out a focused campaign to observe ocean temperatures and long-term climate indicators. The mission combines remote sensing, onboard analysis, and autonomous operations to improve understanding of Earth orbit.', 'Earth orbit', 'planned', NULL),
    (54, 4, 'Ringplane Mapper', 'Ringplane Mapper is carrying out a focused campaign to map volcanic features beneath the dense atmosphere. The mission combines remote sensing, onboard analysis, and autonomous operations to improve understanding of Venus.', 'Venus', 'active', '2015-06-27 12:00:00'),
    (55, 5, 'Saturn Polar Observer', 'Saturn Polar Observer completed a focused campaign to investigate the interaction between the solar wind and the magnetosphere. Its results support comparative studies of Jupiter and help refine designs for future exploration systems.', 'Jupiter', 'completed', '2016-07-01 12:00:00'),
    (56, 6, 'Enceladus Context Scout', 'Enceladus Context Scout attempted to refine models of the Saturnian magnetosphere, but the campaign ended before all objectives were met. The engineering data remains valuable for improving reliability in future Saturn missions.', 'Saturn', 'failed', '2017-08-02 12:00:00'),
    (57, 7, 'Cassini Horizon', 'Cassini Horizon is carrying out a focused campaign to determine the composition of a primitive carbon-rich asteroid. The mission combines remote sensing, onboard analysis, and autonomous operations to improve understanding of the asteroid belt.', 'Asteroid belt', 'planned', NULL),
    (58, 8, 'Saturn Magnetosphere Probe', 'Saturn Magnetosphere Probe is carrying out a focused campaign to search for plume activity and organic compounds. The mission combines remote sensing, onboard analysis, and autonomous operations to improve understanding of Europa.', 'Europa', 'active', '2019-10-04 12:00:00'),
    (59, 9, 'Dione Imaging Survey', 'Dione Imaging Survey completed a focused campaign to map the distribution of dunes and river channels. Its results support comparative studies of Titan and help refine designs for future exploration systems.', 'Titan', 'completed', '2020-11-05 12:00:00'),
    (60, 10, 'Cronian System Explorer', 'Cronian System Explorer attempted to search for transient objects and unexplained high-energy events, but the campaign ended before all objectives were met. The engineering data remains valuable for improving reliability in future deep space missions.', 'Deep space', 'failed', '2021-12-06 12:00:00'),
    (61, 1, 'Ceres Mineral Scout', 'Ceres Mineral Scout is carrying out a focused campaign to map permanently shadowed craters for water ice. The mission combines remote sensing, onboard analysis, and autonomous operations to improve understanding of the Moon.', 'Moon', 'planned', NULL),
    (62, 2, 'Vesta Proximity Demo', 'Vesta Proximity Demo is carrying out a focused campaign to collect mineral samples from an ancient river delta. The mission combines remote sensing, onboard analysis, and autonomous operations to improve understanding of Mars.', 'Mars', 'active', '2023-02-08 12:00:00'),
    (63, 3, 'Carbon Dawn Explorer', 'Carbon Dawn Explorer completed a focused campaign to measure changes in the upper atmosphere and ionosphere. Its results support comparative studies of Earth orbit and help refine designs for future exploration systems.', 'Earth orbit', 'completed', '2024-03-09 12:00:00'),
    (64, 4, 'Asteroid Regolith Lab', 'Asteroid Regolith Lab attempted to test instrumentation designed to survive extreme thermal conditions, but the campaign ended before all objectives were met. The engineering data remains valuable for improving reliability in future Venus missions.', 'Venus', 'failed', '2025-04-10 12:00:00'),
    (65, 5, 'Pallas Composition Survey', 'Pallas Composition Survey is carrying out a focused campaign to measure the planet''''s magnetic field and radiation environment. The mission combines remote sensing, onboard analysis, and autonomous operations to improve understanding of Jupiter.', 'Jupiter', 'planned', NULL),
    (66, 6, 'Beltwatch Pathfinder', 'Beltwatch Pathfinder is carrying out a focused campaign to study atmospheric circulation and polar storm activity. The mission combines remote sensing, onboard analysis, and autonomous operations to improve understanding of Saturn.', 'Saturn', 'active', '2011-06-12 12:00:00'),
    (67, 7, 'Primitive Worlds Mapper', 'Primitive Worlds Mapper completed a focused campaign to search for hydrated minerals and evidence of past alteration. Its results support comparative studies of the asteroid belt and help refine designs for future exploration systems.', 'Asteroid belt', 'completed', '2012-07-13 12:00:00'),
    (68, 8, 'Nysa Sample Scout', 'Nysa Sample Scout attempted to measure the moon''''s induced magnetic field, but the campaign ended before all objectives were met. The engineering data remains valuable for improving reliability in future Europa missions.', 'Europa', 'failed', '2013-08-14 12:00:00'),
    (69, 9, 'Asteroid NavTest', 'Asteroid NavTest is carrying out a focused campaign to study methane-based weather cycles and surface lakes. The mission combines remote sensing, onboard analysis, and autonomous operations to improve understanding of Titan.', 'Titan', 'planned', NULL),
    (70, 10, 'Main Belt Geologist', 'Main Belt Geologist is carrying out a focused campaign to measure the local interstellar environment. The mission combines remote sensing, onboard analysis, and autonomous operations to improve understanding of deep space.', 'Deep space', 'active', '2015-10-16 12:00:00'),
    (71, 1, 'Europa IceShell Mapper', 'Europa IceShell Mapper completed a focused campaign to deploy a compact seismic network to study the lunar interior. Its results support comparative studies of the Moon and help refine designs for future exploration systems.', 'Moon', 'completed', '2016-11-17 12:00:00'),
    (72, 2, 'Oceanworld Plume Scout', 'Oceanworld Plume Scout attempted to evaluate technologies for a future sample-return campaign, but the campaign ended before all objectives were met. The engineering data remains valuable for improving reliability in future Mars missions.', 'Mars', 'failed', '2017-12-18 12:00:00'),
    (73, 3, 'Europa Fracture Survey', 'Europa Fracture Survey is carrying out a focused campaign to observe ocean temperatures and long-term climate indicators. The mission combines remote sensing, onboard analysis, and autonomous operations to improve understanding of Earth orbit.', 'Earth orbit', 'planned', NULL),
    (74, 4, 'Galileo Magnetic Probe', 'Galileo Magnetic Probe is carrying out a focused campaign to map volcanic features beneath the dense atmosphere. The mission combines remote sensing, onboard analysis, and autonomous operations to improve understanding of Venus.', 'Venus', 'active', '2019-02-20 12:00:00'),
    (75, 5, 'Thrace Landing Pathfinder', 'Thrace Landing Pathfinder completed a focused campaign to investigate the interaction between the solar wind and the magnetosphere. Its results support comparative studies of Jupiter and help refine designs for future exploration systems.', 'Jupiter', 'completed', '2020-03-21 12:00:00'),
    (76, 6, 'Europa Organic Chemistry Lab', 'Europa Organic Chemistry Lab attempted to refine models of the Saturnian magnetosphere, but the campaign ended before all objectives were met. The engineering data remains valuable for improving reliability in future Saturn missions.', 'Saturn', 'failed', '2021-04-22 12:00:00'),
    (77, 7, 'Ice Ridge Orbiter', 'Ice Ridge Orbiter is carrying out a focused campaign to determine the composition of a primitive carbon-rich asteroid. The mission combines remote sensing, onboard analysis, and autonomous operations to improve understanding of the asteroid belt.', 'Asteroid belt', 'planned', NULL),
    (78, 8, 'Jupiter Moon Network', 'Jupiter Moon Network is carrying out a focused campaign to search for plume activity and organic compounds. The mission combines remote sensing, onboard analysis, and autonomous operations to improve understanding of Europa.', 'Europa', 'active', '2023-06-24 12:00:00'),
    (79, 9, 'Europa Surface Context', 'Europa Surface Context completed a focused campaign to map the distribution of dunes and river channels. Its results support comparative studies of Titan and help refine designs for future exploration systems.', 'Titan', 'completed', '2024-07-25 12:00:00'),
    (80, 10, 'Ocean Beacon', 'Ocean Beacon attempted to search for transient objects and unexplained high-energy events, but the campaign ended before all objectives were met. The engineering data remains valuable for improving reliability in future deep space missions.', 'Deep space', 'failed', '2025-08-26 12:00:00'),
    (81, 1, 'Titan Methane Survey', 'Titan Methane Survey is carrying out a focused campaign to map permanently shadowed craters for water ice. The mission combines remote sensing, onboard analysis, and autonomous operations to improve understanding of the Moon.', 'Moon', 'planned', NULL),
    (82, 2, 'Dragonfly Atmosphere Lab', 'Dragonfly Atmosphere Lab is carrying out a focused campaign to collect mineral samples from an ancient river delta. The mission combines remote sensing, onboard analysis, and autonomous operations to improve understanding of Mars.', 'Mars', 'active', '2011-10-01 12:00:00'),
    (83, 3, 'Kraken Mare Mapper', 'Kraken Mare Mapper completed a focused campaign to measure changes in the upper atmosphere and ionosphere. Its results support comparative studies of Earth orbit and help refine designs for future exploration systems.', 'Earth orbit', 'completed', '2012-11-02 12:00:00'),
    (84, 4, 'Titan Dune Explorer', 'Titan Dune Explorer attempted to test instrumentation designed to survive extreme thermal conditions, but the campaign ended before all objectives were met. The engineering data remains valuable for improving reliability in future Venus missions.', 'Venus', 'failed', '2013-12-03 12:00:00'),
    (85, 5, 'Huygens Horizon', 'Huygens Horizon is carrying out a focused campaign to measure the planet''''s magnetic field and radiation environment. The mission combines remote sensing, onboard analysis, and autonomous operations to improve understanding of Jupiter.', 'Jupiter', 'planned', NULL),
    (86, 6, 'Saturn Moon Flight Demo', 'Saturn Moon Flight Demo is carrying out a focused campaign to study atmospheric circulation and polar storm activity. The mission combines remote sensing, onboard analysis, and autonomous operations to improve understanding of Saturn.', 'Saturn', 'active', '2015-02-05 12:00:00'),
    (87, 7, 'Titan Organic Atlas', 'Titan Organic Atlas completed a focused campaign to search for hydrated minerals and evidence of past alteration. Its results support comparative studies of the asteroid belt and help refine designs for future exploration systems.', 'Asteroid belt', 'completed', '2016-03-06 12:00:00'),
    (88, 8, 'Xanadu Terrain Survey', 'Xanadu Terrain Survey attempted to measure the moon''''s induced magnetic field, but the campaign ended before all objectives were met. The engineering data remains valuable for improving reliability in future Europa missions.', 'Europa', 'failed', '2017-04-07 12:00:00'),
    (89, 9, 'Titan Climate Relay', 'Titan Climate Relay is carrying out a focused campaign to study methane-based weather cycles and surface lakes. The mission combines remote sensing, onboard analysis, and autonomous operations to improve understanding of Titan.', 'Titan', 'planned', NULL),
    (90, 10, 'Cronus Aviation Pathfinder', 'Cronus Aviation Pathfinder is carrying out a focused campaign to measure the local interstellar environment. The mission combines remote sensing, onboard analysis, and autonomous operations to improve understanding of deep space.', 'Deep space', 'active', '2019-06-09 12:00:00'),
    (91, 1, 'Interstellar Boundary Scout', 'Interstellar Boundary Scout completed a focused campaign to deploy a compact seismic network to study the lunar interior. Its results support comparative studies of the Moon and help refine designs for future exploration systems.', 'Moon', 'completed', '2020-07-10 12:00:00'),
    (92, 2, 'Deep Space Relay One', 'Deep Space Relay One attempted to evaluate technologies for a future sample-return campaign, but the campaign ended before all objectives were met. The engineering data remains valuable for improving reliability in future Mars missions.', 'Mars', 'failed', '2021-08-11 12:00:00'),
    (93, 3, 'Voyager Horizon Survey', 'Voyager Horizon Survey is carrying out a focused campaign to observe ocean temperatures and long-term climate indicators. The mission combines remote sensing, onboard analysis, and autonomous operations to improve understanding of Earth orbit.', 'Earth orbit', 'planned', NULL),
    (94, 4, 'Heliosphere Mapper', 'Heliosphere Mapper is carrying out a focused campaign to map volcanic features beneath the dense atmosphere. The mission combines remote sensing, onboard analysis, and autonomous operations to improve understanding of Venus.', 'Venus', 'active', '2023-10-13 12:00:00'),
    (95, 5, 'Longway Communications Demo', 'Longway Communications Demo completed a focused campaign to investigate the interaction between the solar wind and the magnetosphere. Its results support comparative studies of Jupiter and help refine designs for future exploration systems.', 'Jupiter', 'completed', '2024-11-14 12:00:00'),
    (96, 6, 'Farfield Transient Survey', 'Farfield Transient Survey attempted to refine models of the Saturnian magnetosphere, but the campaign ended before all objectives were met. The engineering data remains valuable for improving reliability in future Saturn missions.', 'Saturn', 'failed', '2025-12-15 12:00:00'),
    (97, 7, 'Pioneer Navigation Lab', 'Pioneer Navigation Lab is carrying out a focused campaign to determine the composition of a primitive carbon-rich asteroid. The mission combines remote sensing, onboard analysis, and autonomous operations to improve understanding of the asteroid belt.', 'Asteroid belt', 'planned', NULL),
    (98, 8, 'Starlight Autonomous Probe', 'Starlight Autonomous Probe is carrying out a focused campaign to search for plume activity and organic compounds. The mission combines remote sensing, onboard analysis, and autonomous operations to improve understanding of Europa.', 'Europa', 'active', '2011-02-17 12:00:00'),
    (99, 9, 'Outer Reach Observatory', 'Outer Reach Observatory completed a focused campaign to map the distribution of dunes and river channels. Its results support comparative studies of Titan and help refine designs for future exploration systems.', 'Titan', 'completed', '2012-03-18 12:00:00'),
    (100, 10, 'Interstellar Pathfinder', 'Interstellar Pathfinder attempted to search for transient objects and unexplained high-energy events, but the campaign ended before all objectives were met. The engineering data remains valuable for improving reliability in future deep space missions.', 'Deep space', 'failed', '2013-04-19 12:00:00');

-- Search and filtering taxonomy.
INSERT INTO tags (tag_id, name, slug) VALUES
    (1, 'Moon', 'moon'),
    (2, 'Mars', 'mars'),
    (3, 'Earth Orbit', 'earth-orbit'),
    (4, 'Venus', 'venus'),
    (5, 'Jupiter', 'jupiter'),
    (6, 'Saturn', 'saturn'),
    (7, 'Asteroid Belt', 'asteroid-belt'),
    (8, 'Europa', 'europa'),
    (9, 'Titan', 'titan'),
    (10, 'Deep Space', 'deep-space'),
    (11, 'Planetary Science', 'planetary-science'),
    (12, 'Crewed', 'crewed'),
    (13, 'Robotic', 'robotic'),
    (14, 'Exploration', 'exploration'),
    (15, 'Research', 'research'),
    (16, 'Technology', 'technology'),
    (17, 'Navigation', 'navigation'),
    (18, 'Climate', 'climate'),
    (19, 'Geology', 'geology'),
    (20, 'Atmosphere', 'atmosphere'),
    (21, 'Sample Return', 'sample-return'),
    (22, 'Human Spaceflight', 'human-spaceflight'),
    (23, 'Uncrewed', 'uncrewed'),
    (24, 'Orbital', 'orbital'),
    (25, 'Lunar', 'lunar'),
    (26, 'Martian', 'martian'),
    (27, 'Outer Solar System', 'outer-solar-system'),
    (28, 'International', 'international'),
    (29, 'Commercial', 'commercial'),
    (30, 'Long Duration', 'long-duration');

-- Each mission receives four deterministic tags.
INSERT INTO mission_tags (mission_id, tag_id) VALUES
    (1, 1),
    (1, 11),
    (1, 3),
    (1, 7),
    (2, 2),
    (2, 12),
    (2, 6),
    (2, 14),
    (3, 3),
    (3, 13),
    (3, 9),
    (3, 21),
    (4, 4),
    (4, 14),
    (4, 12),
    (4, 28),
    (5, 5),
    (5, 15),
    (6, 6),
    (6, 16),
    (6, 18),
    (6, 12),
    (7, 7),
    (7, 17),
    (7, 21),
    (7, 19),
    (8, 8),
    (8, 18),
    (8, 24),
    (8, 26),
    (9, 9),
    (9, 19),
    (9, 27),
    (9, 3),
    (10, 10),
    (10, 20),
    (10, 30),
    (11, 11),
    (11, 21),
    (11, 3),
    (11, 17),
    (12, 12),
    (12, 22),
    (12, 6),
    (12, 24),
    (13, 13),
    (13, 23),
    (13, 9),
    (13, 1),
    (14, 14),
    (14, 24),
    (14, 12),
    (14, 8),
    (15, 15),
    (15, 25),
    (16, 16),
    (16, 26),
    (16, 18),
    (16, 22),
    (17, 17),
    (17, 27),
    (17, 21),
    (17, 29),
    (18, 18),
    (18, 28),
    (18, 24),
    (18, 6),
    (19, 19),
    (19, 29),
    (19, 27),
    (19, 13),
    (20, 20),
    (20, 30),
    (21, 21),
    (21, 1),
    (21, 3),
    (21, 27),
    (22, 22),
    (22, 2),
    (22, 6),
    (22, 4),
    (23, 23),
    (23, 3),
    (23, 9),
    (23, 11),
    (24, 24),
    (24, 4),
    (24, 12),
    (24, 18),
    (25, 25),
    (25, 5),
    (25, 15),
    (26, 26),
    (26, 6),
    (26, 18),
    (26, 2),
    (27, 27),
    (27, 7),
    (27, 21),
    (27, 9),
    (28, 28),
    (28, 8),
    (28, 24),
    (28, 16),
    (29, 29),
    (29, 9),
    (29, 27),
    (29, 23),
    (30, 30),
    (30, 10),
    (31, 1),
    (31, 11),
    (31, 3),
    (31, 7),
    (32, 2),
    (32, 12),
    (32, 6),
    (32, 14),
    (33, 3),
    (33, 13),
    (33, 9),
    (33, 21),
    (34, 4),
    (34, 14),
    (34, 12),
    (34, 28),
    (35, 5),
    (35, 15),
    (36, 6),
    (36, 16),
    (36, 18),
    (36, 12),
    (37, 7),
    (37, 17),
    (37, 21),
    (37, 19),
    (38, 8),
    (38, 18),
    (38, 24),
    (38, 26),
    (39, 9),
    (39, 19),
    (39, 27),
    (39, 3),
    (40, 10),
    (40, 20),
    (40, 30),
    (41, 11),
    (41, 21),
    (41, 3),
    (41, 17),
    (42, 12),
    (42, 22),
    (42, 6),
    (42, 24),
    (43, 13),
    (43, 23),
    (43, 9),
    (43, 1),
    (44, 14),
    (44, 24),
    (44, 12),
    (44, 8),
    (45, 15),
    (45, 25),
    (46, 16),
    (46, 26),
    (46, 18),
    (46, 22),
    (47, 17),
    (47, 27),
    (47, 21),
    (47, 29),
    (48, 18),
    (48, 28),
    (48, 24),
    (48, 6),
    (49, 19),
    (49, 29),
    (49, 27),
    (49, 13),
    (50, 20),
    (50, 30),
    (51, 21),
    (51, 1),
    (51, 3),
    (51, 27),
    (52, 22),
    (52, 2),
    (52, 6),
    (52, 4),
    (53, 23),
    (53, 3),
    (53, 9),
    (53, 11),
    (54, 24),
    (54, 4),
    (54, 12),
    (54, 18),
    (55, 25),
    (55, 5),
    (55, 15),
    (56, 26),
    (56, 6),
    (56, 18),
    (56, 2),
    (57, 27),
    (57, 7),
    (57, 21),
    (57, 9),
    (58, 28),
    (58, 8),
    (58, 24),
    (58, 16),
    (59, 29),
    (59, 9),
    (59, 27),
    (59, 23),
    (60, 30),
    (60, 10),
    (61, 1),
    (61, 11),
    (61, 3),
    (61, 7),
    (62, 2),
    (62, 12),
    (62, 6),
    (62, 14),
    (63, 3),
    (63, 13),
    (63, 9),
    (63, 21),
    (64, 4),
    (64, 14),
    (64, 12),
    (64, 28),
    (65, 5),
    (65, 15),
    (66, 6),
    (66, 16),
    (66, 18),
    (66, 12),
    (67, 7),
    (67, 17),
    (67, 21),
    (67, 19),
    (68, 8),
    (68, 18),
    (68, 24),
    (68, 26),
    (69, 9),
    (69, 19),
    (69, 27),
    (69, 3),
    (70, 10),
    (70, 20),
    (70, 30),
    (71, 11),
    (71, 21),
    (71, 3),
    (71, 17),
    (72, 12),
    (72, 22),
    (72, 6),
    (72, 24),
    (73, 13),
    (73, 23),
    (73, 9),
    (73, 1),
    (74, 14),
    (74, 24),
    (74, 12),
    (74, 8),
    (75, 15),
    (75, 25),
    (76, 16),
    (76, 26),
    (76, 18),
    (76, 22),
    (77, 17),
    (77, 27),
    (77, 21),
    (77, 29),
    (78, 18),
    (78, 28),
    (78, 24),
    (78, 6),
    (79, 19),
    (79, 29),
    (79, 27),
    (79, 13),
    (80, 20),
    (80, 30),
    (81, 21),
    (81, 1),
    (81, 3),
    (81, 27),
    (82, 22),
    (82, 2),
    (82, 6),
    (82, 4),
    (83, 23),
    (83, 3),
    (83, 9),
    (83, 11),
    (84, 24),
    (84, 4),
    (84, 12),
    (84, 18),
    (85, 25),
    (85, 5),
    (85, 15),
    (86, 26),
    (86, 6),
    (86, 18),
    (86, 2),
    (87, 27),
    (87, 7),
    (87, 21),
    (87, 9),
    (88, 28),
    (88, 8),
    (88, 24),
    (88, 16),
    (89, 29),
    (89, 9),
    (89, 27),
    (89, 23),
    (90, 30),
    (90, 10),
    (91, 1),
    (91, 11),
    (91, 3),
    (91, 7),
    (92, 2),
    (92, 12),
    (92, 6),
    (92, 14),
    (93, 3),
    (93, 13),
    (93, 9),
    (93, 21),
    (94, 4),
    (94, 14),
    (94, 12),
    (94, 28),
    (95, 5),
    (95, 15),
    (96, 6),
    (96, 16),
    (96, 18),
    (96, 12),
    (97, 7),
    (97, 17),
    (97, 21),
    (97, 19),
    (98, 8),
    (98, 18),
    (98, 24),
    (98, 26),
    (99, 9),
    (99, 19),
    (99, 27),
    (99, 3),
    (100, 10),
    (100, 20),
    (100, 30);

COMMIT;
